# **📥Data Loading & Reading**

# Importing Pandas Library

In [ ]:
import pandas as pd

# 1. Loading the Dataset

In [ ]:
from google.colab import files

uploaded = files.upload()
file_path = next(iter(uploaded))

df = pd.read_csv(file_path)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
0,PL-0001,2004-04-11,UPA (2004-May2014),All India Pre-Medical Test (AIPMT/CBSE-PMT) 2004,Central Board of Secondary Education (CBSE),Central,All India,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),Physics and chemistry papers leaked in New Del...,2.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2004/20040412/mai...,High
1,PL-0002,2006-06-01,UPA (2004-May2014),Himachal Pradesh Combined Pre-Medical Test (HP...,Himachal Pradesh University,State,Himachal Pradesh,Confirmed,Retest + Arrests-FIR,HP-CPMT medical entrance paper leaked via a to...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2006/20060831/him...,Medium
2,PL-0003,2008-01-01,UPA (2004-May2014),Vyapam Patwari Recruitment Examination 2008,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Accused produced forged educational certificat...,NaN,10.0,NaN,NaN,NaN,The420.in,https://the420.in/vyapam-scam-cbi-court-patwar...,High
3,PL-0004,2009-07-08,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2009,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Paid solvers/impersonators sat the exam in pla...,NaN,NaN,114.0,NaN,NaN,The Free Press Journal,https://www.freepressjournal.in/education/indo...,High
4,PL-0005,2010-06-06,UPA (2004-May2014),RRB Mumbai 2010 recruitment exam (Assistant Lo...,"Railway Recruitment Board (RRB), Mumbai",Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),CBI registered a case on 15 June 2010 over the...,15.0,10.0,NaN,NaN,NaN,The Week,https://www.theweek.in/wire-updates/national/2...,High
5,PL-0006,2011-01-01,UPA (2004-May2014),Vyapam Contract Teacher Eligibility Test (Samv...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Marks of 84 favoured candidates were inflated ...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
6,PL-0007,2011-02-17,UPA (2004-May2014),CBSE Class 10 & Class 12 Board Examinations 2011,Central Board of Secondary Education (CBSE),Central,Andaman & Nicobar Islands,Confirmed,Retest + Arrests-FIR,Class 12 English/Maths and Class 10 science pa...,3.0,4.0,NaN,NaN,NaN,icbse.com,https://www.icbse.com/news/cbse-question-paper...,High
7,PL-0008,2011-05-01,UPA (2004-May2014),AIEEE (All India Engineering Entrance Examinat...,Central Board of Secondary Education (CBSE),Central,Uttar Pradesh (Kanpur/Lucknow),Confirmed,Retest + Arrests-FIR,Paper found being sold in UP (allegedly for ~R...,1.0,NaN,32000.0,NaN,NaN,icbse.com,https://www.icbse.com/news/aieee-2011-question...,High
8,PL-0009,2011-06-19,UPA (2004-May2014),Chhattisgarh Pre-Medical Test (CG-PMT) 2011,Chhattisgarh Professional Examination Board (C...,State,Chhattisgarh,Confirmed,Exam cancelled + Arrests-FIR,CG-PMT scrapped after a crime-branch raid at a...,12.0,NaN,20000.0,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/chhatis...,High
9,PL-0010,2011-11-13,UPA (2004-May2014),Uttar Pradesh Teacher Eligibility Test (UPTET)...,UP Secondary Education Board / Directorate of ...,State,Uttar Pradesh,Confirmed,Arrests-FIR + Probe (SIT),Marks-manipulation/bribery racket (candidates ...,12.0,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/up-seco...,High
10,PL-0011,2012-01-01,UPA (2004-May2014),MP Food Inspector Selection Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Result/answer-sheet rigging to pass favoured c...,NaN,NaN,NaN,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Low
11,PL-0012,2012-01-01,UPA (2004-May2014),MP Pre-PG (Post-Graduate Medical) Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Vyapam officials supplied photocopied model an...,NaN,NaN,NaN,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Low
12,PL-0013,2012-01-01,UPA (2004-May2014),MP Transport Constable Recruitment Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),OMR sheets were altered by Vyapam employees to...,NaN,NaN,NaN,NaN,NaN,Outlook India,https://www.outlookindia.com/national/india-ne...,Medium
13,PL-0014,2012-01-08,UPA (2004-May2014),AIIMS Post-Graduate (MD/MS) Entrance Examinati...,All India Institute of Medical Sciences (AIIMS),Central,Delhi,Confirmed,Arrests-FIR,Gang photographed the PG entrance paper inside...,7.0,NaN,NaN,NaN,NaN,Careerindia,https://www.careerindia.com/news/2012/01/16/tw...,Medium
14,PL-0015,2012-03-01,UPA (2004-May2014),Karnataka Second PU (Class 12) Board Examinati...,"Dept. of Pre-University Education, Karnataka",State,Karnataka,Confirmed,Arrests-FIR + Probe,"Physics, Maths and Biology papers were stolen ...",10.0,NaN,NaN,NaN,NaN,Careerindia,https://www.careerindia.com/news/2012/04/05/ka...,High
15,PL-0016,2012-06-01,UPA (2004-May2014),Jammu & Kashmir Common Entrance Test (JKCET) 2...,J&K Board of Professional Entrance Examination...,State,Jammu & Kashmir,Confirmed,Arrests-FIR + Probe,Medical entrance papers with answer keys were ...,NaN,11.0,NaN,NaN,NaN,Greater Kashmir,https://www.greaterkashmir.com/kashmir/bopee-s...,High
16,PL-0017,2012-06-01,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Fraud combined impersonation by paid solvers w...,NaN,NaN,286.0,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Medium
17,PL-0018,2012-09-30,UPA (2004-May2014),Vyapam Police Constable Recruitment Examinatio...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Candidates arranged impersonators to sit the 3...,NaN,11.0,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/madhya-pradesh/vya...,High
18,PL-0019,2013-01-01,UPA (2004-May2014),Agricultural Development Officer & combined co...,Assam Public Service Commission (APSC),State,Assam,Confirmed,Arrests-FIR + Probe (CBI/SIT),"""Cash-for-jobs"" scam: OMR sheets altered and m...",NaN,34.0,NaN,NaN,NaN,The Assam Tribune,https://assamtribune.com/assam/rakesh-paul-33-...,High
19,PL-0020,2013-01-01,UPA (2004-May2014),Vyapam Police Constable Recruitment Examinatio...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Impersonation and forgery in the 2013 constabl...,NaN,31.0,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/news/india/2013-po...,High
20,PL-0021,2013-04-21,UPA (2004-May2014),SSC Combined Graduate Level (CGL) Examination ...,Staff Selection Commission (SSC),Central,All India,Confirmed,Retest + Arrests-FIR,Question paper leaked and solved off-site; Del...,9.0,NaN,NaN,NaN,NaN,SSC Portal,https://sscportal.in/news/si-exam-topper-caugh...,High
21,PL-0022,2013-07-07,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2013,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),On the night before the 7 July 2013 exam Indor...,20.0,NaN,NaN,23.0,"SCAM-WIDE, not this single exam: the MP SIT ac...",Careers360,https://news.careers360.com/vyapam-scam-five-s...,High
22,PL-0023,2013-10-26,UPA (2004-May2014),RAS (Rajasthan Administrative Service) Prelimi...,Rajasthan Public Service Commission (RPSC),State,Rajasthan,Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),RAS-2013 prelims (26 Oct 2013) scrapped after ...,NaN,NaN,NaN,1.0,Not an aspirant: the alleged mastermind of the...,Careers360,https://news.careers360.com/rajasthan-ras-pape...,High
23,PL-0024,2014-03-05,UPA (2004-May2014),CBSE Class 12 Physics Board Examination 2014,Central Board of Secondary Education (CBSE),Central,Manipur (Imphal),Confirmed,Exam cancelled + Retest + Arrests-FIR,All three sets of the Class 12 Physics paper w...,NaN,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/latest-...,High
24,PL-0025,2014-06-29,NDA (May2014-now),"DSSSB Head Clerk (Grade II DASS, Post Code 90/...",Delhi Subordinate Services Selection Board (DS...,State,Delhi (NCT of Delhi),Alleged,Exam cancelled + Probe,Complaints (Oct 2014-Mar 2015) alleged leakage...,NaN,NaN,NaN,NaN,NaN,SCC Online (Supreme Court judgment coverage),https://www.scconline.com/blog/post/2021/03/05...,Medium
25,PL-0026,2015-03-29,NDA (May2014-now),UPPCS Preliminary Examination 2015,Uttar Pradesh Public Service Commission (UPPSC),State,Uttar Pradesh (Lucknow),Confirmed,Exam cancelled+Arrests-FIR,Question paper was photographed about an hour ...,3.0,NaN,450000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
26,PL-0027,2015-05-03,NDA (May2014-now),AIPMT 2015 (All India Pre-Medical Test),CBSE,Central,All India,Confirmed,Exam cancelled + Retest + Arrests-FIR,Bluetooth/micro-SIM answer-key racket intercep...,NaN,NaN,600000.0,NaN,NaN,Republic World,https://www.republicworld.com/education/entran...,High
27,PL-0028,2015-11-14,NDA (May2014-now),HTET Level-3 (Haryana Teacher Eligibility Test),Haryana Board of School Education (HBSE),State,Haryana (Jind),Confirmed,Exam cancelled + Arrests-FIR,Board cancelled the Level-3 exam the same day ...,5.0,NaN,137000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/hary...,High
28,PL-0029,2016-01-01,NDA (May2014-now),State Level Selection Test (SLST) 2016 teacher...,West Bengal School Service Commission (WBSSC),State,West Bengal,Confirmed,Exam cancelled + Probe (CBI/SIT),OMR-sheet manipulation and appointments beyond...,NaN,NaN,25752.0,NaN,NaN,DD News,https://ddnews.gov.in/en/west-bengal-teacher-r...,High
29,PL-0030,2016-03-06,NDA (May2014-now),Village Panchayat Development Officer (VPDO/VD...,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand,Confirmed,Exam cancelled + Probe (ED/PMLA) + Arrests-FIR,VPDO exam held 6 Mar 2016 was cancelled on 1 D...,17.0,NaN,NaN,NaN,NaN,Prokerala (PTI),https://www.prokerala.com/news/articles/a15886...,Medium
30,PL-0031,2016-05-01,NDA (May2014-now),NEET-UG 2016 (Phase II),CBSE,Central,All India,Denied,None reported,Inter-state leak allegations around the 2016 N...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
31,PL-0032,2017-02-05,NDA (May2014-now),BSSC 1st Inter-Level Combined (Clerical-grade)...,Bihar Staff Selection Commission (BSSC),State,Bihar (Patna) / Jharkhand (arrest),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),The clerical-grade recruitment paper was leake...,30.0,NaN,NaN,NaN,NaN,The Tribune (PTI),https://www.tribuneindia.com/news/archive/nati...,High
32,PL-0033,2017-05-07,NDA (May2014-now),NEET-UG 2017,CBSE,Central,All India,Alleged,Arrests-FIR,Uttarakhand/Bihar inter-state racket promised ...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
33,PL-0034,2017-07-16,NDA (May2014-now),HCS (Judicial Branch) Preliminary Examination ...,Punjab & Haryana High Court,State,Haryana,Confirmed,Exam cancelled + Arrests-FIR + Probe,A High Court committee found the paper was lea...,NaN,3.0,NaN,NaN,NaN,Careers360,https://news.careers360.com/2017-hcs-exam-pape...,High
34,PL-0035,2017-07-24,NDA (May2014-now),UP Police Inspector (Sub-Inspector/Inspector) ...,UP Police Recruitment and Promotion Board (UPP...,State,Uttar Pradesh,Confirmed,Exam cancelled+Probe (STF),"The online recruitment test for 3,307 inspecto...",NaN,NaN,120000.0,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
35,PL-0036,2017-10-29,NDA (May2014-now),DSSSB Primary Teacher (PRT) Recruitment Exam f...,Delhi Subordinate Services Selection Board (DS...,State,Delhi (NCT of Delhi),Confirmed,Exam cancelled + Retest + Arrests-FIR,Question papers of the PRT exam held on 29 Oct...,NaN,NaN,70000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/delh...,High
36,PL-0037,2018-02-21,NDA (May2014-now),SSC CGL 2017 Tier-II,SSC,Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),Answer key of the 21 Feb 2018 Tier-II paper we...,3.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
37,PL-0038,2018-03-26,NDA (May2014-now),CBSE Class 12 Economics board exam 2018,CBSE,Central,All India,Confirmed,Retest + Arrests-FIR,Question paper photographed and circulated on ...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/cbse-paper-leak-cl...,High
38,PL-0039,2018-03-28,NDA (May2014-now),CBSE Class 10 Mathematics board exam 2018,CBSE,Central,All India,Confirmed,Arrests-FIR,Class 10 Maths paper leaked/circulated before ...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/cbse-paper-leak-cl...,High
39,PL-0040,2018-03-31,NDA (May2014-now),UPPCL Junior Engineer / Technician online recr...,Uttar Pradesh Power Corporation Ltd (UPPCL),State,Uttar Pradesh,Confirmed,Exam cancelled+Probe (SIT/STF),UPPCL nullified its 2018 online recruitment ex...,NaN,NaN,NaN,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
40,PL-0041,2018-09-02,NDA (May2014-now),UPSSSC Tubewell Operator (Nalkoop Chalak) Recr...,Uttar Pradesh Subordinate Services Selection C...,State,Uttar Pradesh (Meerut),Confirmed,Exam cancelled+Arrests-FIR,The Hindi question paper leaked and was sold f...,11.0,NaN,250000.0,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
41,PL-0042,2019-11-17,NDA (May2014-now),Non-Secretariat Clerk recruitment exam,Gujarat Subordinate Services Selection Board (...,State,Gujarat,Confirmed,Exam cancelled,Clerk exam cancelled in December 2019 after al...,NaN,NaN,NaN,NaN,NaN,The Federal,https://thefederal.com/states/west/gujarat/aft...,Medium
42,PL-0043,2019-12-29,NDA (May2014-now),Librarian Grade III recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur/Kota/Ajmer),Confirmed,Exam cancelled + Arrests-FIR,Question paper and answer key circulated on Wh...,6.0,NaN,55000.0,NaN,NaN,Daijiworld,https://daijiworld.com/news/newsDisplay?newsID...,High
43,PL-0044,2020-01-01,NDA (May2014-now),Teacher Eligibility Test (TET) 2020,Maharashtra State Council of Examination (MSCE),State,Maharashtra,Confirmed,Arrests-FIR + Probe (CBI/SIT),Marks of thousands of candidates manipulated f...,13.0,NaN,7800.0,NaN,NaN,Careers360,https://news.careers360.com/tet-case-ias-offic...,High
44,PL-0045,2020-09-20,NDA (May2014-now),Sub-Inspector (unarmed branch) written exam,"State Level Police Recruitment Board (SLPRB), ...",State,Assam,Confirmed,Exam cancelled + Arrests-FIR,Paper circulated on WhatsApp the morning of th...,3.0,NaN,66000.0,NaN,NaN,The Sentinel,https://www.sentinelassam.com/north-east-india...,High
45,PL-0046,2020-10-11,NDA (May2014-now),Medical Officer (Dental) recruitment test,Baba Farid University of Health Sciences (BFUHS),State,"Punjab (leak traced to Goindwal Sahib, Tarn Ta...",Confirmed,Exam cancelled + Retest,Question paper for the dental officer post wen...,NaN,NaN,11000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/1-957...,High
46,PL-0047,2020-12-06,NDA (May2014-now),Junior Engineer (JEN) recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur),Confirmed,Exam cancelled + Arrests-FIR + Retest,Paper leaked from a Jaipur government school a...,24.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-je-recru...,High
47,PL-0048,2021-01-03,NDA (May2014-now),Railway GDCE 2021 (General Departmental Compet...,Railway Recruitment Cell (Western Railway),Central,Gujarat,Confirmed,Arrests-FIR + Probe (CBI/SIT),Candidates allegedly supplied papers with answ...,NaN,NaN,8600.0,NaN,NaN,ThePrint,https://theprint.in/india/railways-exam-paper-...,High
48,PL-0049,2021-01-09,NDA (May2014-now),HSSC Gram Sachiv (Panchayat Secretary) exam,Haryana Staff Selection Commission (HSSC),State,Haryana (Hisar),Confirmed,Exam cancelled + Arrests-FIR,Exams held Jan 9-10 for 697 posts were cancell...,18.0,NaN,800000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/paper...,High
49,PL-0050,2021-02-28,NDA (May2014-now),Army Soldier General Duty Common Entrance Exam...,Indian Army,Central,All India,Confirmed,Exam cancelled + Arrests-FIR,Pan-India recruitment exam cancelled about an ...,3.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/nation/army-...,High
50,PL-0051,2021-07-01,NDA (May2014-now),"Forest Guard, Secretariat Security Guard and a...",Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand,Confirmed,Exam cancelled + Retest,Three UKSSSC exams held in 2021 (graduate-leve...,NaN,NaN,NaN,NaN,NaN,Careers360 (PTI),https://news.careers360.com/uttarakhand-three-...,High
51,PL-0052,2021-08-07,NDA (May2014-now),HSSC Police Constable (Male) recruitment exam,Haryana Staff Selection Commission (HSSC),State,Haryana (Kaithal),Confirmed,Exam cancelled + Arrests-FIR,Written exam cancelled after the paper and ans...,167.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/haryana/four...,High
52,PL-0053,2021-09-12,NDA (May2014-now),NEET-UG 2021,NTA,Central,All India,Confirmed,Arrests-FIR,Invigilator and solver-gang involvement with l...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
53,PL-0054,2021-09-13,NDA (May2014-now),Sub-Inspector (SI) recruitment exam 2021,Rajasthan Public Service Commission (RPSC),State,Rajasthan (statewide),Confirmed,Arrests-FIR + Probe (SIT/SOG) + Exam cancelled,Large-scale paper leak involving two RPSC memb...,54.0,NaN,NaN,NaN,NaN,ETV Bharat,https://www.etvbharat.com/en/!state/rajasthan-...,High
54,PL-0055,2021-09-26,NDA (May2014-now),REET 2021 (Rajasthan Eligibility Exam for Teac...,Board of Secondary Education Rajasthan (BSER/R...,State,Rajasthan,Confirmed,Exam cancelled + Arrests-FIR + Retest,Level-2 paper leak led the state to cancel and...,38.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/reet-2021-rajastha...,High
55,PL-0056,2021-10-03,NDA (May2014-now),Police Sub-Inspector (PSI) recruitment exam,Karnataka State Police / Recruitment Wing,State,Karnataka,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),OMR answer sheets tampered to favour candidate...,30.0,NaN,54041.0,NaN,NaN,The Quint,https://www.thequint.com/news/politics/explain...,High
56,PL-0057,2021-10-23,NDA (May2014-now),Patwari (village revenue officer) recruitment ...,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur/Dausa),Alleged,Arrests-FIR,A coaching-institute owner was arrested for se...,2.0,NaN,1562000.0,NaN,NaN,Careers360,https://news.careers360.com/patwari-exam-coach...,Medium
57,PL-0058,2021-11-28,NDA (May2014-now),Uttar Pradesh Teacher Eligibility Test (UPTET)...,UP Examination Regulatory Authority / Basic Ed...,State,Uttar Pradesh (statewide),Confirmed,Exam cancelled+Arrests-FIR,Paper circulated on WhatsApp in several distri...,23.0,NaN,1999000.0,NaN,NaN,India TV News,https://www.indiatvnews.com/education/news-upt...,High
58,PL-0059,2021-12-04,NDA (May2014-now),Graduate-level (Snatak) recruitment exam,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand (Dehradun/Bijnor),Confirmed,Exam cancelled + Arrests-FIR + Probe (STF/SIT),Graduate-level exam for 854 posts across 13 de...,20.0,NaN,NaN,NaN,NaN,ThePrint (PTI),https://theprint.in/india/20-people-arrested-i...,High
59,PL-0060,2021-12-12,NDA (May2014-now),Head Clerk recruitment exam,Gujarat Subordinate Services Selection Board (...,State,Gujarat,Confirmed,Exam cancelled + Arrests-FIR,Question paper obtained from a printing-press ...,14.0,NaN,88000.0,NaN,NaN,Careers360,https://news.careers360.com/guj-exam-for-recru...,High
60,PL-0061,2021-12-12,NDA (May2014-now),MHADA staff recruitment exam,Maharashtra Housing and Area Development Autho...,State,Maharashtra,Confirmed,Exam cancelled + Arrests-FIR,Three held in Pune (including a question-sette...,3.0,NaN,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/education/news-mha...,High

#2. Displaying the First Five Records

In [ ]:
df.head()

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
0,PL-0001,2004-04-11,UPA (2004-May2014),All India Pre-Medical Test (AIPMT/CBSE-PMT) 2004,Central Board of Secondary Education (CBSE),Central,All India,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),Physics and chemistry papers leaked in New Del...,2.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2004/20040412/mai...,High
1,PL-0002,2006-06-01,UPA (2004-May2014),Himachal Pradesh Combined Pre-Medical Test (HP...,Himachal Pradesh University,State,Himachal Pradesh,Confirmed,Retest + Arrests-FIR,HP-CPMT medical entrance paper leaked via a to...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2006/20060831/him...,Medium
2,PL-0003,2008-01-01,UPA (2004-May2014),Vyapam Patwari Recruitment Examination 2008,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Accused produced forged educational certificat...,NaN,10.0,NaN,NaN,NaN,The420.in,https://the420.in/vyapam-scam-cbi-court-patwar...,High
3,PL-0004,2009-07-08,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2009,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Paid solvers/impersonators sat the exam in pla...,NaN,NaN,114.0,NaN,NaN,The Free Press Journal,https://www.freepressjournal.in/education/indo...,High
4,PL-0005,2010-06-06,UPA (2004-May2014),RRB Mumbai 2010 recruitment exam (Assistant Lo...,"Railway Recruitment Board (RRB), Mumbai",Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),CBI registered a case on 15 June 2010 over the...,15.0,10.0,NaN,NaN,NaN,The Week,https://www.theweek.in/wire-updates/national/2...,High

# 3. Displaying the Last Five Records

In [ ]:
df.tail()

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
105,PL-0106,2026-03-14,NDA (May2014-now),CGBSE Class 12 Hindi Board Examination 2026,Chhattisgarh Board of Secondary Education (CGBSE),State,Chhattisgarh,Confirmed,Exam cancelled+Retest+Arrests-FIR,Class 12 Hindi paper leaked and circulated on ...,3.0,0.0,NaN,NaN,NaN,Careers360,https://news.careers360.com/chhattisgarh-board...,Medium
106,PL-0107,2026-04-12,NDA (May2014-now),Jharkhand Excise Constable Competitive Exam (J...,Jharkhand Staff Selection Commission (JSSC),State,Jharkhand (Ranchi),Alleged,Arrests-FIR+Probe (CBI/SIT),Police busting a cheating racket detained 164 ...,164.0,NaN,NaN,NaN,NaN,ThePrint,https://theprint.in/india/jkhand-159-candidate...,High
107,PL-0108,2026-05-03,NDA (May2014-now),NEET-UG 2026,NTA,Central,All India,Confirmed,Exam cancelled + Retest + Probe (CBI/SIT) + Ar...,A pre-circulated guess paper overlapped with u...,NaN,NaN,2270000.0,13.0,~13 aspirant suicides reported by press amid p...,Wikipedia (2026 NEET controversy),https://en.wikipedia.org/wiki/2026_NEET_contro...,High
108,PL-0109,2026-07-04,NDA (May2014-now),HTET Level-3 / PGT (Haryana Teacher Eligibilit...,Haryana Board of School Education (HBSE),State,Haryana,Alleged,None reported,Congress alleged a paper leak with broken seal...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/haryana/hary...,Medium
109,PL-0110,2026-07-19,NDA (May2014-now),Pharmacist Officer recruitment exam,Baba Farid University of Health Sciences (BFUHS),State,Punjab (Faridkot/Kotkapura/Ferozepur),Denied,Arrests-FIR,Police busted a high-tech cheating racket in w...,7.0,NaN,7000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/polic...,High

# 4. Checking Dataset Dimensions

In [ ]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Number of Rows: 110
Number of Columns: 18

# 5. Displaying Dataset Column Names

In [ ]:
print(df.columns)

Index(['incident_id', 'date', 'era', 'exam_name', 'conducting_body',
       'body_type', 'area', 'leak_status', 'action_taken', 'note', 'arrests',
       'convictions', 'aspirants_affected', 'linked_deaths', 'deaths_note',
       'source_name', 'source_url', 'confidence'],
      dtype='object')

# 6. Checking Data Types of Columns

In [ ]:
df.dtypes

incident_id            object
date                   object
era                    object
exam_name              object
conducting_body        object
body_type              object
area                   object
leak_status            object
action_taken           object
note                   object
arrests               float64
convictions           float64
aspirants_affected    float64
linked_deaths         float64
deaths_note            object
source_name            object
source_url             object
confidence             object
dtype: object

# 7. Inspecting Dataset Information

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         110 non-null    object
 1   date                110 non-null    object
 2   era                 110 non-null    object
 3   exam_name           110 non-null    object
 4   conducting_body     110 non-null    object
 5   body_type           110 non-null    object
 6   area                110 non-null    object
 7   leak_status         110 non-null    object
 8   action_taken        110 non-null    object
 9   note                110 non-null    object
 10  arrests             63 non-null     float64
 11  convictions         10 non-null     float64
 12  aspirants_affected  44 non-null     float64
 13  linked_deaths       4 non-null      float64
 14  deaths_note         4 non-null      object
 15  source_name         110 non-null    object
 16  source_url          110 non-null    object
 17  confidence          110 non-null    object
dtypes: float64(4), object(14)
memory usage: 15.6+ KB

# 8. Generating Descriptive Statistics

In [ ]:
df.describe()

          arrests  convictions  aspirants_affected  linked_deaths
count   63.000000    10.000000        4.400000e+01       4.000000
mean    26.857143    11.400000        5.116265e+05      10.250000
std     46.697329    11.946176        8.905203e+05       9.912114
min      0.000000     0.000000        1.140000e+02       1.000000
25%      4.500000     3.250000        6.325000e+04       3.250000
50%     12.000000    10.000000        1.331030e+05       8.500000
75%     23.500000    11.000000        6.000000e+05      15.500000
max    266.000000    34.000000        4.800000e+06      23.000000

# **🔎Data Acquisition & Filtering**

# 1. Analyzing Leak Status Categories

In [ ]:
df["leak_status"].unique()
print(df['leak_status'].value_counts())

leak_status
Confirmed    89
Alleged      13
Denied        5
Suspected     3
Name: count, dtype: int64

# 2. Exploring Conducting Body Type Categories

In [ ]:
df["body_type"].unique()
print(df['body_type'].value_counts())

body_type
State      88
Central    22
Name: count, dtype: int64

#3. Examining Paper Leak Trends Across Eras

In [ ]:
df["era"].unique()
print(df['era'].value_counts())

era
NDA (May2014-now)     86
UPA (2004-May2014)    24
Name: count, dtype: int64

# 4. Assessing Data Confidence Levels

In [ ]:
df["confidence"].unique()
print(df['confidence'].value_counts())

confidence
High      81
Medium    26
Low        3
Name: count, dtype: int64

# 5. Selecting Required Columns

In [ ]:
selected_data = df[
    [
        "incident_id",
        "date",
        "era",
        "exam_name",
        "conducting_body",
        "body_type",
        "area",
        "leak_status",
        "action_taken",
        "arrests",
        "convictions",
        "aspirants_affected",
        "confidence"
    ]
]
display(selected_data.head())

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,arrests,convictions,aspirants_affected,confidence
0,PL-0001,2004-04-11,UPA (2004-May2014),All India Pre-Medical Test (AIPMT/CBSE-PMT) 2004,Central Board of Secondary Education (CBSE),Central,All India,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),2.0,NaN,NaN,High
1,PL-0002,2006-06-01,UPA (2004-May2014),Himachal Pradesh Combined Pre-Medical Test (HP...,Himachal Pradesh University,State,Himachal Pradesh,Confirmed,Retest + Arrests-FIR,NaN,NaN,NaN,Medium
2,PL-0003,2008-01-01,UPA (2004-May2014),Vyapam Patwari Recruitment Examination 2008,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),NaN,10.0,NaN,High
3,PL-0004,2009-07-08,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2009,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),NaN,NaN,114.0,High
4,PL-0005,2010-06-06,UPA (2004-May2014),RRB Mumbai 2010 recruitment exam (Assistant Lo...,"Railway Recruitment Board (RRB), Mumbai",Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),15.0,10.0,NaN,High

# 6. Filtering Confirmed Paper Leak Cases

In [ ]:
confirmed_leaks = df[df["leak_status"] == "Confirmed"]
display(confirmed_leaks)
print("Number of confirmed leaks: ",confirmed_leaks.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
0,PL-0001,2004-04-11,UPA (2004-May2014),All India Pre-Medical Test (AIPMT/CBSE-PMT) 2004,Central Board of Secondary Education (CBSE),Central,All India,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),Physics and chemistry papers leaked in New Del...,2.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2004/20040412/mai...,High
1,PL-0002,2006-06-01,UPA (2004-May2014),Himachal Pradesh Combined Pre-Medical Test (HP...,Himachal Pradesh University,State,Himachal Pradesh,Confirmed,Retest + Arrests-FIR,HP-CPMT medical entrance paper leaked via a to...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2006/20060831/him...,Medium
2,PL-0003,2008-01-01,UPA (2004-May2014),Vyapam Patwari Recruitment Examination 2008,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Accused produced forged educational certificat...,NaN,10.0,NaN,NaN,NaN,The420.in,https://the420.in/vyapam-scam-cbi-court-patwar...,High
3,PL-0004,2009-07-08,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2009,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Paid solvers/impersonators sat the exam in pla...,NaN,NaN,114.0,NaN,NaN,The Free Press Journal,https://www.freepressjournal.in/education/indo...,High
4,PL-0005,2010-06-06,UPA (2004-May2014),RRB Mumbai 2010 recruitment exam (Assistant Lo...,"Railway Recruitment Board (RRB), Mumbai",Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),CBI registered a case on 15 June 2010 over the...,15.0,10.0,NaN,NaN,NaN,The Week,https://www.theweek.in/wire-updates/national/2...,High
5,PL-0006,2011-01-01,UPA (2004-May2014),Vyapam Contract Teacher Eligibility Test (Samv...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Marks of 84 favoured candidates were inflated ...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
6,PL-0007,2011-02-17,UPA (2004-May2014),CBSE Class 10 & Class 12 Board Examinations 2011,Central Board of Secondary Education (CBSE),Central,Andaman & Nicobar Islands,Confirmed,Retest + Arrests-FIR,Class 12 English/Maths and Class 10 science pa...,3.0,4.0,NaN,NaN,NaN,icbse.com,https://www.icbse.com/news/cbse-question-paper...,High
7,PL-0008,2011-05-01,UPA (2004-May2014),AIEEE (All India Engineering Entrance Examinat...,Central Board of Secondary Education (CBSE),Central,Uttar Pradesh (Kanpur/Lucknow),Confirmed,Retest + Arrests-FIR,Paper found being sold in UP (allegedly for ~R...,1.0,NaN,32000.0,NaN,NaN,icbse.com,https://www.icbse.com/news/aieee-2011-question...,High
8,PL-0009,2011-06-19,UPA (2004-May2014),Chhattisgarh Pre-Medical Test (CG-PMT) 2011,Chhattisgarh Professional Examination Board (C...,State,Chhattisgarh,Confirmed,Exam cancelled + Arrests-FIR,CG-PMT scrapped after a crime-branch raid at a...,12.0,NaN,20000.0,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/chhatis...,High
9,PL-0010,2011-11-13,UPA (2004-May2014),Uttar Pradesh Teacher Eligibility Test (UPTET)...,UP Secondary Education Board / Directorate of ...,State,Uttar Pradesh,Confirmed,Arrests-FIR + Probe (SIT),Marks-manipulation/bribery racket (candidates ...,12.0,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/up-seco...,High
10,PL-0011,2012-01-01,UPA (2004-May2014),MP Food Inspector Selection Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Result/answer-sheet rigging to pass favoured c...,NaN,NaN,NaN,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Low
11,PL-0012,2012-01-01,UPA (2004-May2014),MP Pre-PG (Post-Graduate Medical) Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Vyapam officials supplied photocopied model an...,NaN,NaN,NaN,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Low
12,PL-0013,2012-01-01,UPA (2004-May2014),MP Transport Constable Recruitment Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),OMR sheets were altered by Vyapam employees to...,NaN,NaN,NaN,NaN,NaN,Outlook India,https://www.outlookindia.com/national/india-ne...,Medium
13,PL-0014,2012-01-08,UPA (2004-May2014),AIIMS Post-Graduate (MD/MS) Entrance Examinati...,All India Institute of Medical Sciences (AIIMS),Central,Delhi,Confirmed,Arrests-FIR,Gang photographed the PG entrance paper inside...,7.0,NaN,NaN,NaN,NaN,Careerindia,https://www.careerindia.com/news/2012/01/16/tw...,Medium
14,PL-0015,2012-03-01,UPA (2004-May2014),Karnataka Second PU (Class 12) Board Examinati...,"Dept. of Pre-University Education, Karnataka",State,Karnataka,Confirmed,Arrests-FIR + Probe,"Physics, Maths and Biology papers were stolen ...",10.0,NaN,NaN,NaN,NaN,Careerindia,https://www.careerindia.com/news/2012/04/05/ka...,High
15,PL-0016,2012-06-01,UPA (2004-May2014),Jammu & Kashmir Common Entrance Test (JKCET) 2...,J&K Board of Professional Entrance Examination...,State,Jammu & Kashmir,Confirmed,Arrests-FIR + Probe,Medical entrance papers with answer keys were ...,NaN,11.0,NaN,NaN,NaN,Greater Kashmir,https://www.greaterkashmir.com/kashmir/bopee-s...,High
16,PL-0017,2012-06-01,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Fraud combined impersonation by paid solvers w...,NaN,NaN,286.0,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Medium
17,PL-0018,2012-09-30,UPA (2004-May2014),Vyapam Police Constable Recruitment Examinatio...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Candidates arranged impersonators to sit the 3...,NaN,11.0,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/madhya-pradesh/vya...,High
18,PL-0019,2013-01-01,UPA (2004-May2014),Agricultural Development Officer & combined co...,Assam Public Service Commission (APSC),State,Assam,Confirmed,Arrests-FIR + Probe (CBI/SIT),"""Cash-for-jobs"" scam: OMR sheets altered and m...",NaN,34.0,NaN,NaN,NaN,The Assam Tribune,https://assamtribune.com/assam/rakesh-paul-33-...,High
19,PL-0020,2013-01-01,UPA (2004-May2014),Vyapam Police Constable Recruitment Examinatio...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Impersonation and forgery in the 2013 constabl...,NaN,31.0,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/news/india/2013-po...,High
20,PL-0021,2013-04-21,UPA (2004-May2014),SSC Combined Graduate Level (CGL) Examination ...,Staff Selection Commission (SSC),Central,All India,Confirmed,Retest + Arrests-FIR,Question paper leaked and solved off-site; Del...,9.0,NaN,NaN,NaN,NaN,SSC Portal,https://sscportal.in/news/si-exam-topper-caugh...,High
21,PL-0022,2013-07-07,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2013,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),On the night before the 7 July 2013 exam Indor...,20.0,NaN,NaN,23.0,"SCAM-WIDE, not this single exam: the MP SIT ac...",Careers360,https://news.careers360.com/vyapam-scam-five-s...,High
22,PL-0023,2013-10-26,UPA (2004-May2014),RAS (Rajasthan Administrative Service) Prelimi...,Rajasthan Public Service Commission (RPSC),State,Rajasthan,Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),RAS-2013 prelims (26 Oct 2013) scrapped after ...,NaN,NaN,NaN,1.0,Not an aspirant: the alleged mastermind of the...,Careers360,https://news.careers360.com/rajasthan-ras-pape...,High
23,PL-0024,2014-03-05,UPA (2004-May2014),CBSE Class 12 Physics Board Examination 2014,Central Board of Secondary Education (CBSE),Central,Manipur (Imphal),Confirmed,Exam cancelled + Retest + Arrests-FIR,All three sets of the Class 12 Physics paper w...,NaN,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/latest-...,High
25,PL-0026,2015-03-29,NDA (May2014-now),UPPCS Preliminary Examination 2015,Uttar Pradesh Public Service Commission (UPPSC),State,Uttar Pradesh (Lucknow),Confirmed,Exam cancelled+Arrests-FIR,Question paper was photographed about an hour ...,3.0,NaN,450000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
26,PL-0027,2015-05-03,NDA (May2014-now),AIPMT 2015 (All India Pre-Medical Test),CBSE,Central,All India,Confirmed,Exam cancelled + Retest + Arrests-FIR,Bluetooth/micro-SIM answer-key racket intercep...,NaN,NaN,600000.0,NaN,NaN,Republic World,https://www.republicworld.com/education/entran...,High
27,PL-0028,2015-11-14,NDA (May2014-now),HTET Level-3 (Haryana Teacher Eligibility Test),Haryana Board of School Education (HBSE),State,Haryana (Jind),Confirmed,Exam cancelled + Arrests-FIR,Board cancelled the Level-3 exam the same day ...,5.0,NaN,137000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/hary...,High
28,PL-0029,2016-01-01,NDA (May2014-now),State Level Selection Test (SLST) 2016 teacher...,West Bengal School Service Commission (WBSSC),State,West Bengal,Confirmed,Exam cancelled + Probe (CBI/SIT),OMR-sheet manipulation and appointments beyond...,NaN,NaN,25752.0,NaN,NaN,DD News,https://ddnews.gov.in/en/west-bengal-teacher-r...,High
29,PL-0030,2016-03-06,NDA (May2014-now),Village Panchayat Development Officer (VPDO/VD...,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand,Confirmed,Exam cancelled + Probe (ED/PMLA) + Arrests-FIR,VPDO exam held 6 Mar 2016 was cancelled on 1 D...,17.0,NaN,NaN,NaN,NaN,Prokerala (PTI),https://www.prokerala.com/news/articles/a15886...,Medium
31,PL-0032,2017-02-05,NDA (May2014-now),BSSC 1st Inter-Level Combined (Clerical-grade)...,Bihar Staff Selection Commission (BSSC),State,Bihar (Patna) / Jharkhand (arrest),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),The clerical-grade recruitment paper was leake...,30.0,NaN,NaN,NaN,NaN,The Tribune (PTI),https://www.tribuneindia.com/news/archive/nati...,High
33,PL-0034,2017-07-16,NDA (May2014-now),HCS (Judicial Branch) Preliminary Examination ...,Punjab & Haryana High Court,State,Haryana,Confirmed,Exam cancelled + Arrests-FIR + Probe,A High Court committee found the paper was lea...,NaN,3.0,NaN,NaN,NaN,Careers360,https://news.careers360.com/2017-hcs-exam-pape...,High
34,PL-0035,2017-07-24,NDA (May2014-now),UP Police Inspector (Sub-Inspector/Inspector) ...,UP Police Recruitment and Promotion Board (UPP...,State,Uttar Pradesh,Confirmed,Exam cancelled+Probe (STF),"The online recruitment test for 3,307 inspecto...",NaN,NaN,120000.0,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
35,PL-0036,2017-10-29,NDA (May2014-now),DSSSB Primary Teacher (PRT) Recruitment Exam f...,Delhi Subordinate Services Selection Board (DS...,State,Delhi (NCT of Delhi),Confirmed,Exam cancelled + Retest + Arrests-FIR,Question papers of the PRT exam held on 29 Oct...,NaN,NaN,70000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/delh...,High
36,PL-0037,2018-02-21,NDA (May2014-now),SSC CGL 2017 Tier-II,SSC,Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),Answer key of the 21 Feb 2018 Tier-II paper we...,3.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
37,PL-0038,2018-03-26,NDA (May2014-now),CBSE Class 12 Economics board exam 2018,CBSE,Central,All India,Confirmed,Retest + Arrests-FIR,Question paper photographed and circulated on ...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/cbse-paper-leak-cl...,High
38,PL-0039,2018-03-28,NDA (May2014-now),CBSE Class 10 Mathematics board exam 2018,CBSE,Central,All India,Confirmed,Arrests-FIR,Class 10 Maths paper leaked/circulated before ...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/cbse-paper-leak-cl...,High
39,PL-0040,2018-03-31,NDA (May2014-now),UPPCL Junior Engineer / Technician online recr...,Uttar Pradesh Power Corporation Ltd (UPPCL),State,Uttar Pradesh,Confirmed,Exam cancelled+Probe (SIT/STF),UPPCL nullified its 2018 online recruitment ex...,NaN,NaN,NaN,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
40,PL-0041,2018-09-02,NDA (May2014-now),UPSSSC Tubewell Operator (Nalkoop Chalak) Recr...,Uttar Pradesh Subordinate Services Selection C...,State,Uttar Pradesh (Meerut),Confirmed,Exam cancelled+Arrests-FIR,The Hindi question paper leaked and was sold f...,11.0,NaN,250000.0,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
41,PL-0042,2019-11-17,NDA (May2014-now),Non-Secretariat Clerk recruitment exam,Gujarat Subordinate Services Selection Board (...,State,Gujarat,Confirmed,Exam cancelled,Clerk exam cancelled in December 2019 after al...,NaN,NaN,NaN,NaN,NaN,The Federal,https://thefederal.com/states/west/gujarat/aft...,Medium
42,PL-0043,2019-12-29,NDA (May2014-now),Librarian Grade III recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur/Kota/Ajmer),Confirmed,Exam cancelled + Arrests-FIR,Question paper and answer key circulated on Wh...,6.0,NaN,55000.0,NaN,NaN,Daijiworld,https://daijiworld.com/news/newsDisplay?newsID...,High
43,PL-0044,2020-01-01,NDA (May2014-now),Teacher Eligibility Test (TET) 2020,Maharashtra State Council of Examination (MSCE),State,Maharashtra,Confirmed,Arrests-FIR + Probe (CBI/SIT),Marks of thousands of candidates manipulated f...,13.0,NaN,7800.0,NaN,NaN,Careers360,https://news.careers360.com/tet-case-ias-offic...,High
44,PL-0045,2020-09-20,NDA (May2014-now),Sub-Inspector (unarmed branch) written exam,"State Level Police Recruitment Board (SLPRB), ...",State,Assam,Confirmed,Exam cancelled + Arrests-FIR,Paper circulated on WhatsApp the morning of th...,3.0,NaN,66000.0,NaN,NaN,The Sentinel,https://www.sentinelassam.com/north-east-india...,High
45,PL-0046,2020-10-11,NDA (May2014-now),Medical Officer (Dental) recruitment test,Baba Farid University of Health Sciences (BFUHS),State,"Punjab (leak traced to Goindwal Sahib, Tarn Ta...",Confirmed,Exam cancelled + Retest,Question paper for the dental officer post wen...,NaN,NaN,11000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/1-957...,High
46,PL-0047,2020-12-06,NDA (May2014-now),Junior Engineer (JEN) recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur),Confirmed,Exam cancelled + Arrests-FIR + Retest,Paper leaked from a Jaipur government school a...,24.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-je-recru...,High
47,PL-0048,2021-01-03,NDA (May2014-now),Railway GDCE 2021 (General Departmental Compet...,Railway Recruitment Cell (Western Railway),Central,Gujarat,Confirmed,Arrests-FIR + Probe (CBI/SIT),Candidates allegedly supplied papers with answ...,NaN,NaN,8600.0,NaN,NaN,ThePrint,https://theprint.in/india/railways-exam-paper-...,High
48,PL-0049,2021-01-09,NDA (May2014-now),HSSC Gram Sachiv (Panchayat Secretary) exam,Haryana Staff Selection Commission (HSSC),State,Haryana (Hisar),Confirmed,Exam cancelled + Arrests-FIR,Exams held Jan 9-10 for 697 posts were cancell...,18.0,NaN,800000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/paper...,High
49,PL-0050,2021-02-28,NDA (May2014-now),Army Soldier General Duty Common Entrance Exam...,Indian Army,Central,All India,Confirmed,Exam cancelled + Arrests-FIR,Pan-India recruitment exam cancelled about an ...,3.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/nation/army-...,High
50,PL-0051,2021-07-01,NDA (May2014-now),"Forest Guard, Secretariat Security Guard and a...",Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand,Confirmed,Exam cancelled + Retest,Three UKSSSC exams held in 2021 (graduate-leve...,NaN,NaN,NaN,NaN,NaN,Careers360 (PTI),https://news.careers360.com/uttarakhand-three-...,High
51,PL-0052,2021-08-07,NDA (May2014-now),HSSC Police Constable (Male) recruitment exam,Haryana Staff Selection Commission (HSSC),State,Haryana (Kaithal),Confirmed,Exam cancelled + Arrests-FIR,Written exam cancelled after the paper and ans...,167.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/haryana/four...,High
52,PL-0053,2021-09-12,NDA (May2014-now),NEET-UG 2021,NTA,Central,All India,Confirmed,Arrests-FIR,Invigilator and solver-gang involvement with l...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
53,PL-0054,2021-09-13,NDA (May2014-now),Sub-Inspector (SI) recruitment exam 2021,Rajasthan Public Service Commission (RPSC),State,Rajasthan (statewide),Confirmed,Arrests-FIR + Probe (SIT/SOG) + Exam cancelled,Large-scale paper leak involving two RPSC memb...,54.0,NaN,NaN,NaN,NaN,ETV Bharat,https://www.etvbharat.com/en/!state/rajasthan-...,High
54,PL-0055,2021-09-26,NDA (May2014-now),REET 2021 (Rajasthan Eligibility Exam for Teac...,Board of Secondary Education Rajasthan (BSER/R...,State,Rajasthan,Confirmed,Exam cancelled + Arrests-FIR + Retest,Level-2 paper leak led the state to cancel and...,38.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/reet-2021-rajastha...,High
55,PL-0056,2021-10-03,NDA (May2014-now),Police Sub-Inspector (PSI) recruitment exam,Karnataka State Police / Recruitment Wing,State,Karnataka,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),OMR answer sheets tampered to favour candidate...,30.0,NaN,54041.0,NaN,NaN,The Quint,https://www.thequint.com/news/politics/explain...,High
57,PL-0058,2021-11-28,NDA (May2014-now),Uttar Pradesh Teacher Eligibility Test (UPTET)...,UP Examination Regulatory Authority / Basic Ed...,State,Uttar Pradesh (statewide),Confirmed,Exam cancelled+Arrests-FIR,Paper circulated on WhatsApp in several distri...,23.0,NaN,1999000.0,NaN,NaN,India TV News,https://www.indiatvnews.com/education/news-upt...,High
58,PL-0059,2021-12-04,NDA (May2014-now),Graduate-level (Snatak) recruitment exam,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand (Dehradun/Bijnor),Confirmed,Exam cancelled + Arrests-FIR + Probe (STF/SIT),Graduate-level exam for 854 posts across 13 de...,20.0,NaN,NaN,NaN,NaN,ThePrint (PTI),https://theprint.in/india/20-people-arrested-i...,High
59,PL-0060,2021-12-12,NDA (May2014-now),Head Clerk recruitment exam,Gujarat Subordinate Services Selection Board (...,State,Gujarat,Confirmed,Exam cancelled + Arrests-FIR,Question paper obtained from a printing-press ...,14.0,NaN,88000.0,NaN,NaN,Careers360,https://news.careers360.com/guj-exam-for-recru...,High
60,PL-0061,2021-12-12,NDA (May2014-now),MHADA staff recruitment exam,Maharashtra Housing and Area Development Autho...,State,Maharashtra,Confirmed,Exam cancelled + Arrests-FIR,Three held in Pune (including a question-sette...,3.0,NaN,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/education/news-mha...,High
61,PL-0062,2022-02-13,NDA (May2014-now),Class 10 Science & Class 12 Maths revision exams,Tamil Nadu School Education Department,State,Tamil Nadu (Tiruvannamalai),Confirmed,None reported,Papers from two private schools photographed a...,NaN,NaN,NaN,NaN,NaN,The News Minute,https://www.thenewsminute.com/article/tn-revis...,Medium
62,PL-0063,2022-03-01,NDA (May2014-now),Lower Division Clerk (LDC) recruitment exam,Rajasthan High Court,State,Rajasthan (Jodhpur),Confirmed,Exam cancelled,The High Court's LDC recruitment paper was lea...,NaN,NaN,NaN,NaN,NaN,Daijiworld,https://daijiworld.com/news/newsDisplay?newsID...,Medium
64,PL-0065,2022-03-27,NDA (May2014-now),Himachal Pradesh Police Constable Recruitment ...,Himachal Pradesh Police (state government recr...,State,Himachal Pradesh,Confirmed,Exam cancelled + Retest + Arrests-FIR + Probe ...,"Written test held 27 March 2022 for 1,334 cons...",88.0,NaN,75000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/himachal/cbi...,High

Number of confirmed leaks:  (89, 18)

# 7. Filtering Alleged Paper Leak Cases

In [ ]:
alleged_cases = df[df["leak_status"] == "Alleged"]

display(alleged_cases)
print("Shape of Alleged Cases:", alleged_cases.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
24,PL-0025,2014-06-29,NDA (May2014-now),"DSSSB Head Clerk (Grade II DASS, Post Code 90/...",Delhi Subordinate Services Selection Board (DS...,State,Delhi (NCT of Delhi),Alleged,Exam cancelled + Probe,Complaints (Oct 2014-Mar 2015) alleged leakage...,NaN,NaN,NaN,NaN,NaN,SCC Online (Supreme Court judgment coverage),https://www.scconline.com/blog/post/2021/03/05...,Medium
32,PL-0033,2017-05-07,NDA (May2014-now),NEET-UG 2017,CBSE,Central,All India,Alleged,Arrests-FIR,Uttarakhand/Bihar inter-state racket promised ...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
56,PL-0057,2021-10-23,NDA (May2014-now),Patwari (village revenue officer) recruitment ...,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur/Dausa),Alleged,Arrests-FIR,A coaching-institute owner was arrested for se...,2.0,NaN,1562000.0,NaN,NaN,Careers360,https://news.careers360.com/patwari-exam-coach...,Medium
63,PL-0064,2022-03-27,NDA (May2014-now),Forest Guard recruitment exam,Gujarat University / State Forest Department,State,Gujarat,Alleged,Arrests-FIR,A candidate in Mehsana was found with a full a...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/gujarat-forest-gua...,Medium
70,PL-0071,2022-07-31,NDA (May2014-now),UPSSSC Lekhpal (Mains) Recruitment Exam 2022,Uttar Pradesh Subordinate Services Selection C...,State,Uttar Pradesh,Alleged,Arrests-FIR,21 people including solvers and impersonators ...,21.0,NaN,250000.0,NaN,NaN,ThePrint,https://theprint.in/india/up-lekhpal-exam-solv...,High
78,PL-0079,2023-02-25,NDA (May2014-now),REET 2023 (teacher eligibility test),Board of Secondary Education Rajasthan (BSER/R...,State,Rajasthan (Jodhpur),Alleged,Arrests-FIR,Police raided a Jodhpur marriage hall hours be...,37.0,NaN,NaN,NaN,NaN,Free Press Journal,https://www.freepressjournal.in/education/reet...,Medium
80,PL-0081,2023-03-15,NDA (May2014-now),MP Patwari Recruitment Exam 2023 (Group-2 Sub-...,"Madhya Pradesh Employees Selection Board (ESB,...",State,Madhya Pradesh,Alleged,Probe,"After 30 Jun 2023 results, aspirants and Congr...",NaN,NaN,974000.0,NaN,NaN,The Week,https://www.theweek.in/news/india/2023/07/13/m...,Medium
81,PL-0082,2023-05-11,NDA (May2014-now),CGPSC State Service Examination 2021 (recruitm...,Chhattisgarh Public Service Commission (CGPSC),State,Chhattisgarh,Alleged,Probe (CBI/SIT)+Arrests-FIR,CBI probe into nepotism/favouritism in recruit...,12.0,0.0,129206.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/chhattisgarh...,High
85,PL-0086,2023-08-17,NDA (May2014-now),Talathi (village accountant) recruitment exam,Maharashtra Revenue Dept / TCS-ION (conducting...,State,Maharashtra,Alleged,Arrests-FIR,A repeat paper-leak suspect caught in Nashik o...,NaN,NaN,865000.0,NaN,NaN,Lokmat Times,https://www.lokmattimes.com/maharashtra/leaks-...,Medium
96,PL-0097,2024-09-21,NDA (May2014-now),JSSC CGL / JGGLCCE (re-conducted exam),Jharkhand Staff Selection Commission (JSSC),State,Jharkhand,Alleged,Arrests-FIR+Probe (CBI/SIT),Paper-leak allegations dogged the re-held CGL ...,10.0,NaN,304769.0,NaN,NaN,ThePrint,https://theprint.in/india/5-irb-jawans-among-8...,High
98,PL-0099,2024-12-13,NDA (May2014-now),BPSC 70th Combined Competitive Exam (Prelims),Bihar Public Service Commission (BPSC),State,"Bihar (Bapu Exam Centre, Patna)",Alleged,Retest,Candidates at the Bapu Pariksha Parisar centre...,NaN,NaN,480000.0,NaN,NaN,Careers360,https://news.careers360.com/bpsc-70th-cce-re-e...,High
106,PL-0107,2026-04-12,NDA (May2014-now),Jharkhand Excise Constable Competitive Exam (J...,Jharkhand Staff Selection Commission (JSSC),State,Jharkhand (Ranchi),Alleged,Arrests-FIR+Probe (CBI/SIT),Police busting a cheating racket detained 164 ...,164.0,NaN,NaN,NaN,NaN,ThePrint,https://theprint.in/india/jkhand-159-candidate...,High
108,PL-0109,2026-07-04,NDA (May2014-now),HTET Level-3 / PGT (Haryana Teacher Eligibilit...,Haryana Board of School Education (HBSE),State,Haryana,Alleged,None reported,Congress alleged a paper leak with broken seal...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/haryana/hary...,Medium

Shape of Alleged Cases: (13, 18)

# 8. Filtering Denied Paper Leak Cases

In [ ]:
denied_cases = df[df["leak_status"] == "Denied"]

display(denied_cases)
print("Shape of Denied Cases:", denied_cases.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
30,PL-0031,2016-05-01,NDA (May2014-now),NEET-UG 2016 (Phase II),CBSE,Central,All India,Denied,None reported,Inter-state leak allegations around the 2016 N...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
91,PL-0092,2024-03-17,NDA (May2014-now),JPSC Combined Civil Services Preliminary Exam ...,Jharkhand Public Service Commission (JPSC),State,Jharkhand (Jamtara/Chatra/Dhanbad),Denied,Probe,"Candidates at centres in Jamtara, Chatra and D...",NaN,NaN,NaN,NaN,NaN,ETV Bharat,https://www.etvbharat.com/en/!state/jharkhand-...,High
93,PL-0094,2024-06-18,NDA (May2014-now),UGC-NET June 2024,NTA,Central,All India,Denied,Exam cancelled + Probe (CBI/SIT),Education Ministry cancelled the exam a day af...,0.0,NaN,900000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/india/cbi-cl...,High
94,PL-0095,2024-06-23,NDA (May2014-now),MPPSC State Service & State Forest Service Pre...,Madhya Pradesh Public Service Commission (MPPSC),State,Madhya Pradesh,Denied,Arrests-FIR + Probe,A Telegram account claimed the General Studies...,NaN,NaN,183000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/india/case-r...,High
109,PL-0110,2026-07-19,NDA (May2014-now),Pharmacist Officer recruitment exam,Baba Farid University of Health Sciences (BFUHS),State,Punjab (Faridkot/Kotkapura/Ferozepur),Denied,Arrests-FIR,Police busted a high-tech cheating racket in w...,7.0,NaN,7000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/polic...,High

Shape of Denied Cases: (5, 18)

# 9. Filtering Suspected Paper Leak Cases

In [ ]:
suspected_cases = df[df["leak_status"] == "Suspected"]

display(suspected_cases)
print("Shape of Suspected Cases:", suspected_cases.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
82,PL-0083,2023-05-25,NDA (May2014-now),MP Forest Guard (Vanrakshak) Recruitment Exam ...,Madhya Pradesh Employees Selection Board (ESB),State,Madhya Pradesh,Suspected,Probe,ESB withheld results of 113 candidates after d...,NaN,NaN,100000.0,NaN,NaN,Bansal News,https://bansalnews.com/mp-forest-guard-bharti-...,Low
95,PL-0096,2024-06-23,NDA (May2014-now),NEET-PG 2024,NBEMS,Central,All India,Suspected,None reported,Postponed ~12 hours before the exam as a preca...,NaN,NaN,240000.0,NaN,NaN,Medical Dialogues,https://medicaldialogues.in/news/education/nee...,Medium
103,PL-0104,2025-12-21,NDA (May2014-now),Group-B recruitment exam (408 posts incl Naib ...,Punjab Subordinate Services Selection Board (P...,State,Punjab (Bathinda highlighted),Suspected,Probe (SIT/VB),Aspirants alleged irregularities (answer-sheet...,NaN,NaN,100000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/bathinda/six...,Medium

Shape of Suspected Cases: (3, 18)

# 10. Filtering Central Conducting Body Cases

In [ ]:
central_cases = df[df["body_type"] == "Central"]

display(central_cases)

print("Number of central_cases : ",central_cases.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
0,PL-0001,2004-04-11,UPA (2004-May2014),All India Pre-Medical Test (AIPMT/CBSE-PMT) 2004,Central Board of Secondary Education (CBSE),Central,All India,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),Physics and chemistry papers leaked in New Del...,2.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2004/20040412/mai...,High
4,PL-0005,2010-06-06,UPA (2004-May2014),RRB Mumbai 2010 recruitment exam (Assistant Lo...,"Railway Recruitment Board (RRB), Mumbai",Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),CBI registered a case on 15 June 2010 over the...,15.0,10.0,NaN,NaN,NaN,The Week,https://www.theweek.in/wire-updates/national/2...,High
6,PL-0007,2011-02-17,UPA (2004-May2014),CBSE Class 10 & Class 12 Board Examinations 2011,Central Board of Secondary Education (CBSE),Central,Andaman & Nicobar Islands,Confirmed,Retest + Arrests-FIR,Class 12 English/Maths and Class 10 science pa...,3.0,4.0,NaN,NaN,NaN,icbse.com,https://www.icbse.com/news/cbse-question-paper...,High
7,PL-0008,2011-05-01,UPA (2004-May2014),AIEEE (All India Engineering Entrance Examinat...,Central Board of Secondary Education (CBSE),Central,Uttar Pradesh (Kanpur/Lucknow),Confirmed,Retest + Arrests-FIR,Paper found being sold in UP (allegedly for ~R...,1.0,NaN,32000.0,NaN,NaN,icbse.com,https://www.icbse.com/news/aieee-2011-question...,High
13,PL-0014,2012-01-08,UPA (2004-May2014),AIIMS Post-Graduate (MD/MS) Entrance Examinati...,All India Institute of Medical Sciences (AIIMS),Central,Delhi,Confirmed,Arrests-FIR,Gang photographed the PG entrance paper inside...,7.0,NaN,NaN,NaN,NaN,Careerindia,https://www.careerindia.com/news/2012/01/16/tw...,Medium
20,PL-0021,2013-04-21,UPA (2004-May2014),SSC Combined Graduate Level (CGL) Examination ...,Staff Selection Commission (SSC),Central,All India,Confirmed,Retest + Arrests-FIR,Question paper leaked and solved off-site; Del...,9.0,NaN,NaN,NaN,NaN,SSC Portal,https://sscportal.in/news/si-exam-topper-caugh...,High
23,PL-0024,2014-03-05,UPA (2004-May2014),CBSE Class 12 Physics Board Examination 2014,Central Board of Secondary Education (CBSE),Central,Manipur (Imphal),Confirmed,Exam cancelled + Retest + Arrests-FIR,All three sets of the Class 12 Physics paper w...,NaN,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/latest-...,High
26,PL-0027,2015-05-03,NDA (May2014-now),AIPMT 2015 (All India Pre-Medical Test),CBSE,Central,All India,Confirmed,Exam cancelled + Retest + Arrests-FIR,Bluetooth/micro-SIM answer-key racket intercep...,NaN,NaN,600000.0,NaN,NaN,Republic World,https://www.republicworld.com/education/entran...,High
30,PL-0031,2016-05-01,NDA (May2014-now),NEET-UG 2016 (Phase II),CBSE,Central,All India,Denied,None reported,Inter-state leak allegations around the 2016 N...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
32,PL-0033,2017-05-07,NDA (May2014-now),NEET-UG 2017,CBSE,Central,All India,Alleged,Arrests-FIR,Uttarakhand/Bihar inter-state racket promised ...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
36,PL-0037,2018-02-21,NDA (May2014-now),SSC CGL 2017 Tier-II,SSC,Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),Answer key of the 21 Feb 2018 Tier-II paper we...,3.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
37,PL-0038,2018-03-26,NDA (May2014-now),CBSE Class 12 Economics board exam 2018,CBSE,Central,All India,Confirmed,Retest + Arrests-FIR,Question paper photographed and circulated on ...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/cbse-paper-leak-cl...,High
38,PL-0039,2018-03-28,NDA (May2014-now),CBSE Class 10 Mathematics board exam 2018,CBSE,Central,All India,Confirmed,Arrests-FIR,Class 10 Maths paper leaked/circulated before ...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/cbse-paper-leak-cl...,High
47,PL-0048,2021-01-03,NDA (May2014-now),Railway GDCE 2021 (General Departmental Compet...,Railway Recruitment Cell (Western Railway),Central,Gujarat,Confirmed,Arrests-FIR + Probe (CBI/SIT),Candidates allegedly supplied papers with answ...,NaN,NaN,8600.0,NaN,NaN,ThePrint,https://theprint.in/india/railways-exam-paper-...,High
49,PL-0050,2021-02-28,NDA (May2014-now),Army Soldier General Duty Common Entrance Exam...,Indian Army,Central,All India,Confirmed,Exam cancelled + Arrests-FIR,Pan-India recruitment exam cancelled about an ...,3.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/nation/army-...,High
52,PL-0053,2021-09-12,NDA (May2014-now),NEET-UG 2021,NTA,Central,All India,Confirmed,Arrests-FIR,Invigilator and solver-gang involvement with l...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
83,PL-0084,2023-06-03,NDA (May2014-now),AIIMS NORCET-4 (Nursing Officer Recruitment),AIIMS New Delhi,Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),Paper leaked via doctored computer monitors gi...,5.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/delhi/cbi-ar...,High
92,PL-0093,2024-05-05,NDA (May2014-now),NEET-UG 2024,NTA,Central,All India,Confirmed,Retest + Arrests-FIR + Probe (CBI/SIT),CBI confirmed a leak confined to Hazaribagh (J...,NaN,NaN,2300000.0,4.0,>=4 NEET aspirants' suicides were reported by ...,National Herald,https://www.nationalheraldindia.com/national/n...,High
93,PL-0094,2024-06-18,NDA (May2014-now),UGC-NET June 2024,NTA,Central,All India,Denied,Exam cancelled + Probe (CBI/SIT),Education Ministry cancelled the exam a day af...,0.0,NaN,900000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/india/cbi-cl...,High
95,PL-0096,2024-06-23,NDA (May2014-now),NEET-PG 2024,NBEMS,Central,All India,Suspected,None reported,Postponed ~12 hours before the exam as a preca...,NaN,NaN,240000.0,NaN,NaN,Medical Dialogues,https://medicaldialogues.in/news/education/nee...,Medium
99,PL-0100,2025-03-04,NDA (May2014-now),East Central Railway departmental promotion ex...,East Central Railway / Railway Board,Central,Uttar Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT) + Exam cancelled,CBI arrested 26 ECR officials at Mughal Sarai ...,26.0,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/railway...,High
107,PL-0108,2026-05-03,NDA (May2014-now),NEET-UG 2026,NTA,Central,All India,Confirmed,Exam cancelled + Retest + Probe (CBI/SIT) + Ar...,A pre-circulated guess paper overlapped with u...,NaN,NaN,2270000.0,13.0,~13 aspirant suicides reported by press amid p...,Wikipedia (2026 NEET controversy),https://en.wikipedia.org/wiki/2026_NEET_contro...,High

Number of central_cases :  (22, 18)

#11.  Filtering State Conducting Body Cases

In [ ]:
state_cases = df[df["body_type"] == "State"]

display(state_cases)

print("Number of state_cases : ",state_cases.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
1,PL-0002,2006-06-01,UPA (2004-May2014),Himachal Pradesh Combined Pre-Medical Test (HP...,Himachal Pradesh University,State,Himachal Pradesh,Confirmed,Retest + Arrests-FIR,HP-CPMT medical entrance paper leaked via a to...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2006/20060831/him...,Medium
2,PL-0003,2008-01-01,UPA (2004-May2014),Vyapam Patwari Recruitment Examination 2008,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Accused produced forged educational certificat...,NaN,10.0,NaN,NaN,NaN,The420.in,https://the420.in/vyapam-scam-cbi-court-patwar...,High
3,PL-0004,2009-07-08,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2009,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Paid solvers/impersonators sat the exam in pla...,NaN,NaN,114.0,NaN,NaN,The Free Press Journal,https://www.freepressjournal.in/education/indo...,High
5,PL-0006,2011-01-01,UPA (2004-May2014),Vyapam Contract Teacher Eligibility Test (Samv...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Marks of 84 favoured candidates were inflated ...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
8,PL-0009,2011-06-19,UPA (2004-May2014),Chhattisgarh Pre-Medical Test (CG-PMT) 2011,Chhattisgarh Professional Examination Board (C...,State,Chhattisgarh,Confirmed,Exam cancelled + Arrests-FIR,CG-PMT scrapped after a crime-branch raid at a...,12.0,NaN,20000.0,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/chhatis...,High
9,PL-0010,2011-11-13,UPA (2004-May2014),Uttar Pradesh Teacher Eligibility Test (UPTET)...,UP Secondary Education Board / Directorate of ...,State,Uttar Pradesh,Confirmed,Arrests-FIR + Probe (SIT),Marks-manipulation/bribery racket (candidates ...,12.0,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/up-seco...,High
10,PL-0011,2012-01-01,UPA (2004-May2014),MP Food Inspector Selection Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Result/answer-sheet rigging to pass favoured c...,NaN,NaN,NaN,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Low
11,PL-0012,2012-01-01,UPA (2004-May2014),MP Pre-PG (Post-Graduate Medical) Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Vyapam officials supplied photocopied model an...,NaN,NaN,NaN,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Low
12,PL-0013,2012-01-01,UPA (2004-May2014),MP Transport Constable Recruitment Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),OMR sheets were altered by Vyapam employees to...,NaN,NaN,NaN,NaN,NaN,Outlook India,https://www.outlookindia.com/national/india-ne...,Medium
14,PL-0015,2012-03-01,UPA (2004-May2014),Karnataka Second PU (Class 12) Board Examinati...,"Dept. of Pre-University Education, Karnataka",State,Karnataka,Confirmed,Arrests-FIR + Probe,"Physics, Maths and Biology papers were stolen ...",10.0,NaN,NaN,NaN,NaN,Careerindia,https://www.careerindia.com/news/2012/04/05/ka...,High
15,PL-0016,2012-06-01,UPA (2004-May2014),Jammu & Kashmir Common Entrance Test (JKCET) 2...,J&K Board of Professional Entrance Examination...,State,Jammu & Kashmir,Confirmed,Arrests-FIR + Probe,Medical entrance papers with answer keys were ...,NaN,11.0,NaN,NaN,NaN,Greater Kashmir,https://www.greaterkashmir.com/kashmir/bopee-s...,High
16,PL-0017,2012-06-01,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Fraud combined impersonation by paid solvers w...,NaN,NaN,286.0,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Medium
17,PL-0018,2012-09-30,UPA (2004-May2014),Vyapam Police Constable Recruitment Examinatio...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Candidates arranged impersonators to sit the 3...,NaN,11.0,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/madhya-pradesh/vya...,High
18,PL-0019,2013-01-01,UPA (2004-May2014),Agricultural Development Officer & combined co...,Assam Public Service Commission (APSC),State,Assam,Confirmed,Arrests-FIR + Probe (CBI/SIT),"""Cash-for-jobs"" scam: OMR sheets altered and m...",NaN,34.0,NaN,NaN,NaN,The Assam Tribune,https://assamtribune.com/assam/rakesh-paul-33-...,High
19,PL-0020,2013-01-01,UPA (2004-May2014),Vyapam Police Constable Recruitment Examinatio...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Impersonation and forgery in the 2013 constabl...,NaN,31.0,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/news/india/2013-po...,High
21,PL-0022,2013-07-07,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2013,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),On the night before the 7 July 2013 exam Indor...,20.0,NaN,NaN,23.0,"SCAM-WIDE, not this single exam: the MP SIT ac...",Careers360,https://news.careers360.com/vyapam-scam-five-s...,High
22,PL-0023,2013-10-26,UPA (2004-May2014),RAS (Rajasthan Administrative Service) Prelimi...,Rajasthan Public Service Commission (RPSC),State,Rajasthan,Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),RAS-2013 prelims (26 Oct 2013) scrapped after ...,NaN,NaN,NaN,1.0,Not an aspirant: the alleged mastermind of the...,Careers360,https://news.careers360.com/rajasthan-ras-pape...,High
24,PL-0025,2014-06-29,NDA (May2014-now),"DSSSB Head Clerk (Grade II DASS, Post Code 90/...",Delhi Subordinate Services Selection Board (DS...,State,Delhi (NCT of Delhi),Alleged,Exam cancelled + Probe,Complaints (Oct 2014-Mar 2015) alleged leakage...,NaN,NaN,NaN,NaN,NaN,SCC Online (Supreme Court judgment coverage),https://www.scconline.com/blog/post/2021/03/05...,Medium
25,PL-0026,2015-03-29,NDA (May2014-now),UPPCS Preliminary Examination 2015,Uttar Pradesh Public Service Commission (UPPSC),State,Uttar Pradesh (Lucknow),Confirmed,Exam cancelled+Arrests-FIR,Question paper was photographed about an hour ...,3.0,NaN,450000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
27,PL-0028,2015-11-14,NDA (May2014-now),HTET Level-3 (Haryana Teacher Eligibility Test),Haryana Board of School Education (HBSE),State,Haryana (Jind),Confirmed,Exam cancelled + Arrests-FIR,Board cancelled the Level-3 exam the same day ...,5.0,NaN,137000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/hary...,High
28,PL-0029,2016-01-01,NDA (May2014-now),State Level Selection Test (SLST) 2016 teacher...,West Bengal School Service Commission (WBSSC),State,West Bengal,Confirmed,Exam cancelled + Probe (CBI/SIT),OMR-sheet manipulation and appointments beyond...,NaN,NaN,25752.0,NaN,NaN,DD News,https://ddnews.gov.in/en/west-bengal-teacher-r...,High
29,PL-0030,2016-03-06,NDA (May2014-now),Village Panchayat Development Officer (VPDO/VD...,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand,Confirmed,Exam cancelled + Probe (ED/PMLA) + Arrests-FIR,VPDO exam held 6 Mar 2016 was cancelled on 1 D...,17.0,NaN,NaN,NaN,NaN,Prokerala (PTI),https://www.prokerala.com/news/articles/a15886...,Medium
31,PL-0032,2017-02-05,NDA (May2014-now),BSSC 1st Inter-Level Combined (Clerical-grade)...,Bihar Staff Selection Commission (BSSC),State,Bihar (Patna) / Jharkhand (arrest),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),The clerical-grade recruitment paper was leake...,30.0,NaN,NaN,NaN,NaN,The Tribune (PTI),https://www.tribuneindia.com/news/archive/nati...,High
33,PL-0034,2017-07-16,NDA (May2014-now),HCS (Judicial Branch) Preliminary Examination ...,Punjab & Haryana High Court,State,Haryana,Confirmed,Exam cancelled + Arrests-FIR + Probe,A High Court committee found the paper was lea...,NaN,3.0,NaN,NaN,NaN,Careers360,https://news.careers360.com/2017-hcs-exam-pape...,High
34,PL-0035,2017-07-24,NDA (May2014-now),UP Police Inspector (Sub-Inspector/Inspector) ...,UP Police Recruitment and Promotion Board (UPP...,State,Uttar Pradesh,Confirmed,Exam cancelled+Probe (STF),"The online recruitment test for 3,307 inspecto...",NaN,NaN,120000.0,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
35,PL-0036,2017-10-29,NDA (May2014-now),DSSSB Primary Teacher (PRT) Recruitment Exam f...,Delhi Subordinate Services Selection Board (DS...,State,Delhi (NCT of Delhi),Confirmed,Exam cancelled + Retest + Arrests-FIR,Question papers of the PRT exam held on 29 Oct...,NaN,NaN,70000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/delh...,High
39,PL-0040,2018-03-31,NDA (May2014-now),UPPCL Junior Engineer / Technician online recr...,Uttar Pradesh Power Corporation Ltd (UPPCL),State,Uttar Pradesh,Confirmed,Exam cancelled+Probe (SIT/STF),UPPCL nullified its 2018 online recruitment ex...,NaN,NaN,NaN,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
40,PL-0041,2018-09-02,NDA (May2014-now),UPSSSC Tubewell Operator (Nalkoop Chalak) Recr...,Uttar Pradesh Subordinate Services Selection C...,State,Uttar Pradesh (Meerut),Confirmed,Exam cancelled+Arrests-FIR,The Hindi question paper leaked and was sold f...,11.0,NaN,250000.0,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
41,PL-0042,2019-11-17,NDA (May2014-now),Non-Secretariat Clerk recruitment exam,Gujarat Subordinate Services Selection Board (...,State,Gujarat,Confirmed,Exam cancelled,Clerk exam cancelled in December 2019 after al...,NaN,NaN,NaN,NaN,NaN,The Federal,https://thefederal.com/states/west/gujarat/aft...,Medium
42,PL-0043,2019-12-29,NDA (May2014-now),Librarian Grade III recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur/Kota/Ajmer),Confirmed,Exam cancelled + Arrests-FIR,Question paper and answer key circulated on Wh...,6.0,NaN,55000.0,NaN,NaN,Daijiworld,https://daijiworld.com/news/newsDisplay?newsID...,High
43,PL-0044,2020-01-01,NDA (May2014-now),Teacher Eligibility Test (TET) 2020,Maharashtra State Council of Examination (MSCE),State,Maharashtra,Confirmed,Arrests-FIR + Probe (CBI/SIT),Marks of thousands of candidates manipulated f...,13.0,NaN,7800.0,NaN,NaN,Careers360,https://news.careers360.com/tet-case-ias-offic...,High
44,PL-0045,2020-09-20,NDA (May2014-now),Sub-Inspector (unarmed branch) written exam,"State Level Police Recruitment Board (SLPRB), ...",State,Assam,Confirmed,Exam cancelled + Arrests-FIR,Paper circulated on WhatsApp the morning of th...,3.0,NaN,66000.0,NaN,NaN,The Sentinel,https://www.sentinelassam.com/north-east-india...,High
45,PL-0046,2020-10-11,NDA (May2014-now),Medical Officer (Dental) recruitment test,Baba Farid University of Health Sciences (BFUHS),State,"Punjab (leak traced to Goindwal Sahib, Tarn Ta...",Confirmed,Exam cancelled + Retest,Question paper for the dental officer post wen...,NaN,NaN,11000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/1-957...,High
46,PL-0047,2020-12-06,NDA (May2014-now),Junior Engineer (JEN) recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur),Confirmed,Exam cancelled + Arrests-FIR + Retest,Paper leaked from a Jaipur government school a...,24.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-je-recru...,High
48,PL-0049,2021-01-09,NDA (May2014-now),HSSC Gram Sachiv (Panchayat Secretary) exam,Haryana Staff Selection Commission (HSSC),State,Haryana (Hisar),Confirmed,Exam cancelled + Arrests-FIR,Exams held Jan 9-10 for 697 posts were cancell...,18.0,NaN,800000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/paper...,High
50,PL-0051,2021-07-01,NDA (May2014-now),"Forest Guard, Secretariat Security Guard and a...",Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand,Confirmed,Exam cancelled + Retest,Three UKSSSC exams held in 2021 (graduate-leve...,NaN,NaN,NaN,NaN,NaN,Careers360 (PTI),https://news.careers360.com/uttarakhand-three-...,High
51,PL-0052,2021-08-07,NDA (May2014-now),HSSC Police Constable (Male) recruitment exam,Haryana Staff Selection Commission (HSSC),State,Haryana (Kaithal),Confirmed,Exam cancelled + Arrests-FIR,Written exam cancelled after the paper and ans...,167.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/haryana/four...,High
53,PL-0054,2021-09-13,NDA (May2014-now),Sub-Inspector (SI) recruitment exam 2021,Rajasthan Public Service Commission (RPSC),State,Rajasthan (statewide),Confirmed,Arrests-FIR + Probe (SIT/SOG) + Exam cancelled,Large-scale paper leak involving two RPSC memb...,54.0,NaN,NaN,NaN,NaN,ETV Bharat,https://www.etvbharat.com/en/!state/rajasthan-...,High
54,PL-0055,2021-09-26,NDA (May2014-now),REET 2021 (Rajasthan Eligibility Exam for Teac...,Board of Secondary Education Rajasthan (BSER/R...,State,Rajasthan,Confirmed,Exam cancelled + Arrests-FIR + Retest,Level-2 paper leak led the state to cancel and...,38.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/reet-2021-rajastha...,High
55,PL-0056,2021-10-03,NDA (May2014-now),Police Sub-Inspector (PSI) recruitment exam,Karnataka State Police / Recruitment Wing,State,Karnataka,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),OMR answer sheets tampered to favour candidate...,30.0,NaN,54041.0,NaN,NaN,The Quint,https://www.thequint.com/news/politics/explain...,High
56,PL-0057,2021-10-23,NDA (May2014-now),Patwari (village revenue officer) recruitment ...,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur/Dausa),Alleged,Arrests-FIR,A coaching-institute owner was arrested for se...,2.0,NaN,1562000.0,NaN,NaN,Careers360,https://news.careers360.com/patwari-exam-coach...,Medium
57,PL-0058,2021-11-28,NDA (May2014-now),Uttar Pradesh Teacher Eligibility Test (UPTET)...,UP Examination Regulatory Authority / Basic Ed...,State,Uttar Pradesh (statewide),Confirmed,Exam cancelled+Arrests-FIR,Paper circulated on WhatsApp in several distri...,23.0,NaN,1999000.0,NaN,NaN,India TV News,https://www.indiatvnews.com/education/news-upt...,High
58,PL-0059,2021-12-04,NDA (May2014-now),Graduate-level (Snatak) recruitment exam,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand (Dehradun/Bijnor),Confirmed,Exam cancelled + Arrests-FIR + Probe (STF/SIT),Graduate-level exam for 854 posts across 13 de...,20.0,NaN,NaN,NaN,NaN,ThePrint (PTI),https://theprint.in/india/20-people-arrested-i...,High
59,PL-0060,2021-12-12,NDA (May2014-now),Head Clerk recruitment exam,Gujarat Subordinate Services Selection Board (...,State,Gujarat,Confirmed,Exam cancelled + Arrests-FIR,Question paper obtained from a printing-press ...,14.0,NaN,88000.0,NaN,NaN,Careers360,https://news.careers360.com/guj-exam-for-recru...,High
60,PL-0061,2021-12-12,NDA (May2014-now),MHADA staff recruitment exam,Maharashtra Housing and Area Development Autho...,State,Maharashtra,Confirmed,Exam cancelled + Arrests-FIR,Three held in Pune (including a question-sette...,3.0,NaN,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/education/news-mha...,High
61,PL-0062,2022-02-13,NDA (May2014-now),Class 10 Science & Class 12 Maths revision exams,Tamil Nadu School Education Department,State,Tamil Nadu (Tiruvannamalai),Confirmed,None reported,Papers from two private schools photographed a...,NaN,NaN,NaN,NaN,NaN,The News Minute,https://www.thenewsminute.com/article/tn-revis...,Medium
62,PL-0063,2022-03-01,NDA (May2014-now),Lower Division Clerk (LDC) recruitment exam,Rajasthan High Court,State,Rajasthan (Jodhpur),Confirmed,Exam cancelled,The High Court's LDC recruitment paper was lea...,NaN,NaN,NaN,NaN,NaN,Daijiworld,https://daijiworld.com/news/newsDisplay?newsID...,Medium
63,PL-0064,2022-03-27,NDA (May2014-now),Forest Guard recruitment exam,Gujarat University / State Forest Department,State,Gujarat,Alleged,Arrests-FIR,A candidate in Mehsana was found with a full a...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/gujarat-forest-gua...,Medium
64,PL-0065,2022-03-27,NDA (May2014-now),Himachal Pradesh Police Constable Recruitment ...,Himachal Pradesh Police (state government recr...,State,Himachal Pradesh,Confirmed,Exam cancelled + Retest + Arrests-FIR + Probe ...,"Written test held 27 March 2022 for 1,334 cons...",88.0,NaN,75000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/himachal/cbi...,High
65,PL-0066,2022-04-27,NDA (May2014-now),SSC (Class 10) board examination,Andhra Pradesh Board of Secondary Education / ...,State,Andhra Pradesh,Confirmed,Arrests-FIR,Teachers on exam duty photographed papers minu...,70.0,NaN,NaN,NaN,NaN,Siasat (archive),https://archive.siasat.com/news/andhra-pradesh...,High
66,PL-0067,2022-05-08,NDA (May2014-now),BPSC 67th Combined Competitive Exam (Prelims),Bihar Public Service Commission (BPSC),State,"Bihar (Ara, Bhojpur)",Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),Question paper screenshots went viral on socia...,4.0,NaN,600000.0,NaN,NaN,Careers360,https://news.careers360.com/bpsc-67th-question...,High
67,PL-0068,2022-05-14,NDA (May2014-now),Rajasthan Police Constable recruitment exam,Rajasthan Police Recruitment & Promotion Board,State,Rajasthan (Jaipur/Jhotwara),Confirmed,Exam cancelled + Arrests-FIR + Retest,Second shift paper was leaked via a screenshot...,8.0,NaN,160000.0,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-police-c...,High
68,PL-0069,2022-05-22,NDA (May2014-now),Naib Tehsildar recruitment test (78 posts),Punjab Public Service Commission (PPSC),State,Punjab (Patiala; centres statewide),Confirmed,Arrests-FIR + Exam cancelled,Dummy candidates photographed question papers ...,5.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/5-arr...,High
69,PL-0070,2022-06-01,NDA (May2014-now),Assistant Engineer / Junior Engineer (AE/JE) r...,Uttarakhand Public Service Commission (UKPSC),State,Uttarakhand (Haridwar),Confirmed,Arrests-FIR + Probe (SIT),AE/JE exam held June 2022; an SIT found the qu...,3.0,NaN,NaN,NaN,NaN,Siasat (PTI),https://archive.siasat.com/news/3-arrested-in-...,High
70,PL-0071,2022-07-31,NDA (May2014-now),UPSSSC Lekhpal (Mains) Recruitment Exam 2022,Uttar Pradesh Subordinate Services Selection C...,State,Uttar Pradesh,Alleged,Arrests-FIR,21 people including solvers and impersonators ...,21.0,NaN,250000.0,NaN,NaN,ThePrint,https://theprint.in/india/up-lekhpal-exam-solv...,High
71,PL-0072,2022-08-26,NDA (May2014-now),Assistant Engineer (Civil) exam,Arunachal Pradesh Public Service Commission (A...,State,Arunachal Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),AE (Civil) paper leaked; APPSC secretary and c...,10.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/appsc-examination-...,High
72,PL-0073,2022-11-12,NDA (May2014-now),Forest Guard recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Rajsamand),Confirmed,Exam cancelled + Arrests-FIR,Evening shift cancelled after a paper-leak gan...,9.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-forest-g...,High
73,PL-0074,2022-12-23,NDA (May2014-now),BSSC 3rd Graduate Level (CGL) Combined Competi...,Bihar Staff Selection Commission (BSSC),State,"Bihar (528 centres, 38 districts)",Confirmed,Exam cancelled + Probe (SIT),Pages of the first-shift question paper (for 2...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/bssc-cgl-question-...,Medium
74,PL-0075,2022-12-24,NDA (May2014-now),Senior Teacher Grade II (2nd Grade Teacher) Ge...,Rajasthan Public Service Commission (RPSC),State,Rajasthan (Udaipur),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT/ED),Candidates were caught solving the leaked GK p...,44.0,NaN,NaN,NaN,NaN,The Print,https://theprint.in/india/rajasthan-2nd-grade-...,High

Number of state_cases :  (88, 18)

# 12. Filtering NDA Era Paper Leak Cases

In [ ]:
nda_cases = df[df["era"] == "NDA (May2014-now)"]
display(nda_cases)
print("Number of nda_cases : ",nda_cases.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
24,PL-0025,2014-06-29,NDA (May2014-now),"DSSSB Head Clerk (Grade II DASS, Post Code 90/...",Delhi Subordinate Services Selection Board (DS...,State,Delhi (NCT of Delhi),Alleged,Exam cancelled + Probe,Complaints (Oct 2014-Mar 2015) alleged leakage...,NaN,NaN,NaN,NaN,NaN,SCC Online (Supreme Court judgment coverage),https://www.scconline.com/blog/post/2021/03/05...,Medium
25,PL-0026,2015-03-29,NDA (May2014-now),UPPCS Preliminary Examination 2015,Uttar Pradesh Public Service Commission (UPPSC),State,Uttar Pradesh (Lucknow),Confirmed,Exam cancelled+Arrests-FIR,Question paper was photographed about an hour ...,3.0,NaN,450000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
26,PL-0027,2015-05-03,NDA (May2014-now),AIPMT 2015 (All India Pre-Medical Test),CBSE,Central,All India,Confirmed,Exam cancelled + Retest + Arrests-FIR,Bluetooth/micro-SIM answer-key racket intercep...,NaN,NaN,600000.0,NaN,NaN,Republic World,https://www.republicworld.com/education/entran...,High
27,PL-0028,2015-11-14,NDA (May2014-now),HTET Level-3 (Haryana Teacher Eligibility Test),Haryana Board of School Education (HBSE),State,Haryana (Jind),Confirmed,Exam cancelled + Arrests-FIR,Board cancelled the Level-3 exam the same day ...,5.0,NaN,137000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/hary...,High
28,PL-0029,2016-01-01,NDA (May2014-now),State Level Selection Test (SLST) 2016 teacher...,West Bengal School Service Commission (WBSSC),State,West Bengal,Confirmed,Exam cancelled + Probe (CBI/SIT),OMR-sheet manipulation and appointments beyond...,NaN,NaN,25752.0,NaN,NaN,DD News,https://ddnews.gov.in/en/west-bengal-teacher-r...,High
29,PL-0030,2016-03-06,NDA (May2014-now),Village Panchayat Development Officer (VPDO/VD...,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand,Confirmed,Exam cancelled + Probe (ED/PMLA) + Arrests-FIR,VPDO exam held 6 Mar 2016 was cancelled on 1 D...,17.0,NaN,NaN,NaN,NaN,Prokerala (PTI),https://www.prokerala.com/news/articles/a15886...,Medium
30,PL-0031,2016-05-01,NDA (May2014-now),NEET-UG 2016 (Phase II),CBSE,Central,All India,Denied,None reported,Inter-state leak allegations around the 2016 N...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
31,PL-0032,2017-02-05,NDA (May2014-now),BSSC 1st Inter-Level Combined (Clerical-grade)...,Bihar Staff Selection Commission (BSSC),State,Bihar (Patna) / Jharkhand (arrest),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),The clerical-grade recruitment paper was leake...,30.0,NaN,NaN,NaN,NaN,The Tribune (PTI),https://www.tribuneindia.com/news/archive/nati...,High
32,PL-0033,2017-05-07,NDA (May2014-now),NEET-UG 2017,CBSE,Central,All India,Alleged,Arrests-FIR,Uttarakhand/Bihar inter-state racket promised ...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
33,PL-0034,2017-07-16,NDA (May2014-now),HCS (Judicial Branch) Preliminary Examination ...,Punjab & Haryana High Court,State,Haryana,Confirmed,Exam cancelled + Arrests-FIR + Probe,A High Court committee found the paper was lea...,NaN,3.0,NaN,NaN,NaN,Careers360,https://news.careers360.com/2017-hcs-exam-pape...,High
34,PL-0035,2017-07-24,NDA (May2014-now),UP Police Inspector (Sub-Inspector/Inspector) ...,UP Police Recruitment and Promotion Board (UPP...,State,Uttar Pradesh,Confirmed,Exam cancelled+Probe (STF),"The online recruitment test for 3,307 inspecto...",NaN,NaN,120000.0,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
35,PL-0036,2017-10-29,NDA (May2014-now),DSSSB Primary Teacher (PRT) Recruitment Exam f...,Delhi Subordinate Services Selection Board (DS...,State,Delhi (NCT of Delhi),Confirmed,Exam cancelled + Retest + Arrests-FIR,Question papers of the PRT exam held on 29 Oct...,NaN,NaN,70000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/delh...,High
36,PL-0037,2018-02-21,NDA (May2014-now),SSC CGL 2017 Tier-II,SSC,Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),Answer key of the 21 Feb 2018 Tier-II paper we...,3.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
37,PL-0038,2018-03-26,NDA (May2014-now),CBSE Class 12 Economics board exam 2018,CBSE,Central,All India,Confirmed,Retest + Arrests-FIR,Question paper photographed and circulated on ...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/cbse-paper-leak-cl...,High
38,PL-0039,2018-03-28,NDA (May2014-now),CBSE Class 10 Mathematics board exam 2018,CBSE,Central,All India,Confirmed,Arrests-FIR,Class 10 Maths paper leaked/circulated before ...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/cbse-paper-leak-cl...,High
39,PL-0040,2018-03-31,NDA (May2014-now),UPPCL Junior Engineer / Technician online recr...,Uttar Pradesh Power Corporation Ltd (UPPCL),State,Uttar Pradesh,Confirmed,Exam cancelled+Probe (SIT/STF),UPPCL nullified its 2018 online recruitment ex...,NaN,NaN,NaN,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
40,PL-0041,2018-09-02,NDA (May2014-now),UPSSSC Tubewell Operator (Nalkoop Chalak) Recr...,Uttar Pradesh Subordinate Services Selection C...,State,Uttar Pradesh (Meerut),Confirmed,Exam cancelled+Arrests-FIR,The Hindi question paper leaked and was sold f...,11.0,NaN,250000.0,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
41,PL-0042,2019-11-17,NDA (May2014-now),Non-Secretariat Clerk recruitment exam,Gujarat Subordinate Services Selection Board (...,State,Gujarat,Confirmed,Exam cancelled,Clerk exam cancelled in December 2019 after al...,NaN,NaN,NaN,NaN,NaN,The Federal,https://thefederal.com/states/west/gujarat/aft...,Medium
42,PL-0043,2019-12-29,NDA (May2014-now),Librarian Grade III recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur/Kota/Ajmer),Confirmed,Exam cancelled + Arrests-FIR,Question paper and answer key circulated on Wh...,6.0,NaN,55000.0,NaN,NaN,Daijiworld,https://daijiworld.com/news/newsDisplay?newsID...,High
43,PL-0044,2020-01-01,NDA (May2014-now),Teacher Eligibility Test (TET) 2020,Maharashtra State Council of Examination (MSCE),State,Maharashtra,Confirmed,Arrests-FIR + Probe (CBI/SIT),Marks of thousands of candidates manipulated f...,13.0,NaN,7800.0,NaN,NaN,Careers360,https://news.careers360.com/tet-case-ias-offic...,High
44,PL-0045,2020-09-20,NDA (May2014-now),Sub-Inspector (unarmed branch) written exam,"State Level Police Recruitment Board (SLPRB), ...",State,Assam,Confirmed,Exam cancelled + Arrests-FIR,Paper circulated on WhatsApp the morning of th...,3.0,NaN,66000.0,NaN,NaN,The Sentinel,https://www.sentinelassam.com/north-east-india...,High
45,PL-0046,2020-10-11,NDA (May2014-now),Medical Officer (Dental) recruitment test,Baba Farid University of Health Sciences (BFUHS),State,"Punjab (leak traced to Goindwal Sahib, Tarn Ta...",Confirmed,Exam cancelled + Retest,Question paper for the dental officer post wen...,NaN,NaN,11000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/1-957...,High
46,PL-0047,2020-12-06,NDA (May2014-now),Junior Engineer (JEN) recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur),Confirmed,Exam cancelled + Arrests-FIR + Retest,Paper leaked from a Jaipur government school a...,24.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-je-recru...,High
47,PL-0048,2021-01-03,NDA (May2014-now),Railway GDCE 2021 (General Departmental Compet...,Railway Recruitment Cell (Western Railway),Central,Gujarat,Confirmed,Arrests-FIR + Probe (CBI/SIT),Candidates allegedly supplied papers with answ...,NaN,NaN,8600.0,NaN,NaN,ThePrint,https://theprint.in/india/railways-exam-paper-...,High
48,PL-0049,2021-01-09,NDA (May2014-now),HSSC Gram Sachiv (Panchayat Secretary) exam,Haryana Staff Selection Commission (HSSC),State,Haryana (Hisar),Confirmed,Exam cancelled + Arrests-FIR,Exams held Jan 9-10 for 697 posts were cancell...,18.0,NaN,800000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/paper...,High
49,PL-0050,2021-02-28,NDA (May2014-now),Army Soldier General Duty Common Entrance Exam...,Indian Army,Central,All India,Confirmed,Exam cancelled + Arrests-FIR,Pan-India recruitment exam cancelled about an ...,3.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/nation/army-...,High
50,PL-0051,2021-07-01,NDA (May2014-now),"Forest Guard, Secretariat Security Guard and a...",Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand,Confirmed,Exam cancelled + Retest,Three UKSSSC exams held in 2021 (graduate-leve...,NaN,NaN,NaN,NaN,NaN,Careers360 (PTI),https://news.careers360.com/uttarakhand-three-...,High
51,PL-0052,2021-08-07,NDA (May2014-now),HSSC Police Constable (Male) recruitment exam,Haryana Staff Selection Commission (HSSC),State,Haryana (Kaithal),Confirmed,Exam cancelled + Arrests-FIR,Written exam cancelled after the paper and ans...,167.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/haryana/four...,High
52,PL-0053,2021-09-12,NDA (May2014-now),NEET-UG 2021,NTA,Central,All India,Confirmed,Arrests-FIR,Invigilator and solver-gang involvement with l...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
53,PL-0054,2021-09-13,NDA (May2014-now),Sub-Inspector (SI) recruitment exam 2021,Rajasthan Public Service Commission (RPSC),State,Rajasthan (statewide),Confirmed,Arrests-FIR + Probe (SIT/SOG) + Exam cancelled,Large-scale paper leak involving two RPSC memb...,54.0,NaN,NaN,NaN,NaN,ETV Bharat,https://www.etvbharat.com/en/!state/rajasthan-...,High
54,PL-0055,2021-09-26,NDA (May2014-now),REET 2021 (Rajasthan Eligibility Exam for Teac...,Board of Secondary Education Rajasthan (BSER/R...,State,Rajasthan,Confirmed,Exam cancelled + Arrests-FIR + Retest,Level-2 paper leak led the state to cancel and...,38.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/reet-2021-rajastha...,High
55,PL-0056,2021-10-03,NDA (May2014-now),Police Sub-Inspector (PSI) recruitment exam,Karnataka State Police / Recruitment Wing,State,Karnataka,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),OMR answer sheets tampered to favour candidate...,30.0,NaN,54041.0,NaN,NaN,The Quint,https://www.thequint.com/news/politics/explain...,High
56,PL-0057,2021-10-23,NDA (May2014-now),Patwari (village revenue officer) recruitment ...,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur/Dausa),Alleged,Arrests-FIR,A coaching-institute owner was arrested for se...,2.0,NaN,1562000.0,NaN,NaN,Careers360,https://news.careers360.com/patwari-exam-coach...,Medium
57,PL-0058,2021-11-28,NDA (May2014-now),Uttar Pradesh Teacher Eligibility Test (UPTET)...,UP Examination Regulatory Authority / Basic Ed...,State,Uttar Pradesh (statewide),Confirmed,Exam cancelled+Arrests-FIR,Paper circulated on WhatsApp in several distri...,23.0,NaN,1999000.0,NaN,NaN,India TV News,https://www.indiatvnews.com/education/news-upt...,High
58,PL-0059,2021-12-04,NDA (May2014-now),Graduate-level (Snatak) recruitment exam,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand (Dehradun/Bijnor),Confirmed,Exam cancelled + Arrests-FIR + Probe (STF/SIT),Graduate-level exam for 854 posts across 13 de...,20.0,NaN,NaN,NaN,NaN,ThePrint (PTI),https://theprint.in/india/20-people-arrested-i...,High
59,PL-0060,2021-12-12,NDA (May2014-now),Head Clerk recruitment exam,Gujarat Subordinate Services Selection Board (...,State,Gujarat,Confirmed,Exam cancelled + Arrests-FIR,Question paper obtained from a printing-press ...,14.0,NaN,88000.0,NaN,NaN,Careers360,https://news.careers360.com/guj-exam-for-recru...,High
60,PL-0061,2021-12-12,NDA (May2014-now),MHADA staff recruitment exam,Maharashtra Housing and Area Development Autho...,State,Maharashtra,Confirmed,Exam cancelled + Arrests-FIR,Three held in Pune (including a question-sette...,3.0,NaN,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/education/news-mha...,High
61,PL-0062,2022-02-13,NDA (May2014-now),Class 10 Science & Class 12 Maths revision exams,Tamil Nadu School Education Department,State,Tamil Nadu (Tiruvannamalai),Confirmed,None reported,Papers from two private schools photographed a...,NaN,NaN,NaN,NaN,NaN,The News Minute,https://www.thenewsminute.com/article/tn-revis...,Medium
62,PL-0063,2022-03-01,NDA (May2014-now),Lower Division Clerk (LDC) recruitment exam,Rajasthan High Court,State,Rajasthan (Jodhpur),Confirmed,Exam cancelled,The High Court's LDC recruitment paper was lea...,NaN,NaN,NaN,NaN,NaN,Daijiworld,https://daijiworld.com/news/newsDisplay?newsID...,Medium
63,PL-0064,2022-03-27,NDA (May2014-now),Forest Guard recruitment exam,Gujarat University / State Forest Department,State,Gujarat,Alleged,Arrests-FIR,A candidate in Mehsana was found with a full a...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/gujarat-forest-gua...,Medium
64,PL-0065,2022-03-27,NDA (May2014-now),Himachal Pradesh Police Constable Recruitment ...,Himachal Pradesh Police (state government recr...,State,Himachal Pradesh,Confirmed,Exam cancelled + Retest + Arrests-FIR + Probe ...,"Written test held 27 March 2022 for 1,334 cons...",88.0,NaN,75000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/himachal/cbi...,High
65,PL-0066,2022-04-27,NDA (May2014-now),SSC (Class 10) board examination,Andhra Pradesh Board of Secondary Education / ...,State,Andhra Pradesh,Confirmed,Arrests-FIR,Teachers on exam duty photographed papers minu...,70.0,NaN,NaN,NaN,NaN,Siasat (archive),https://archive.siasat.com/news/andhra-pradesh...,High
66,PL-0067,2022-05-08,NDA (May2014-now),BPSC 67th Combined Competitive Exam (Prelims),Bihar Public Service Commission (BPSC),State,"Bihar (Ara, Bhojpur)",Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),Question paper screenshots went viral on socia...,4.0,NaN,600000.0,NaN,NaN,Careers360,https://news.careers360.com/bpsc-67th-question...,High
67,PL-0068,2022-05-14,NDA (May2014-now),Rajasthan Police Constable recruitment exam,Rajasthan Police Recruitment & Promotion Board,State,Rajasthan (Jaipur/Jhotwara),Confirmed,Exam cancelled + Arrests-FIR + Retest,Second shift paper was leaked via a screenshot...,8.0,NaN,160000.0,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-police-c...,High
68,PL-0069,2022-05-22,NDA (May2014-now),Naib Tehsildar recruitment test (78 posts),Punjab Public Service Commission (PPSC),State,Punjab (Patiala; centres statewide),Confirmed,Arrests-FIR + Exam cancelled,Dummy candidates photographed question papers ...,5.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/5-arr...,High
69,PL-0070,2022-06-01,NDA (May2014-now),Assistant Engineer / Junior Engineer (AE/JE) r...,Uttarakhand Public Service Commission (UKPSC),State,Uttarakhand (Haridwar),Confirmed,Arrests-FIR + Probe (SIT),AE/JE exam held June 2022; an SIT found the qu...,3.0,NaN,NaN,NaN,NaN,Siasat (PTI),https://archive.siasat.com/news/3-arrested-in-...,High
70,PL-0071,2022-07-31,NDA (May2014-now),UPSSSC Lekhpal (Mains) Recruitment Exam 2022,Uttar Pradesh Subordinate Services Selection C...,State,Uttar Pradesh,Alleged,Arrests-FIR,21 people including solvers and impersonators ...,21.0,NaN,250000.0,NaN,NaN,ThePrint,https://theprint.in/india/up-lekhpal-exam-solv...,High
71,PL-0072,2022-08-26,NDA (May2014-now),Assistant Engineer (Civil) exam,Arunachal Pradesh Public Service Commission (A...,State,Arunachal Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),AE (Civil) paper leaked; APPSC secretary and c...,10.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/appsc-examination-...,High
72,PL-0073,2022-11-12,NDA (May2014-now),Forest Guard recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Rajsamand),Confirmed,Exam cancelled + Arrests-FIR,Evening shift cancelled after a paper-leak gan...,9.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-forest-g...,High
73,PL-0074,2022-12-23,NDA (May2014-now),BSSC 3rd Graduate Level (CGL) Combined Competi...,Bihar Staff Selection Commission (BSSC),State,"Bihar (528 centres, 38 districts)",Confirmed,Exam cancelled + Probe (SIT),Pages of the first-shift question paper (for 2...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/bssc-cgl-question-...,Medium
74,PL-0075,2022-12-24,NDA (May2014-now),Senior Teacher Grade II (2nd Grade Teacher) Ge...,Rajasthan Public Service Commission (RPSC),State,Rajasthan (Udaipur),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT/ED),Candidates were caught solving the leaked GK p...,44.0,NaN,NaN,NaN,NaN,The Print,https://theprint.in/india/rajasthan-2nd-grade-...,High
75,PL-0076,2022-12-25,NDA (May2014-now),Junior Office Assistant (IT) / JOA (IT) Recrui...,Himachal Pradesh Staff Selection Commission (H...,State,Himachal Pradesh (Hamirpur),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT/CBI),Solved JOA (IT) paper and Rs 2.5 lakh were sei...,6.0,NaN,150000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/himachal/jr-...,High
76,PL-0077,2023-01-08,NDA (May2014-now),Patwari / Lekhpal recruitment exam,Uttarakhand Public Service Commission (UKPSC),State,Uttarakhand (Haridwar),Confirmed,Exam cancelled + Retest + Arrests-FIR,Patwari-Lekhpal exam for 563 posts held 8 Jan ...,5.0,NaN,100000.0,NaN,NaN,Careers360 (PTI),https://news.careers360.com/after-series-of-pa...,High
77,PL-0078,2023-01-29,NDA (May2014-now),GPSSB Junior Clerk recruitment exam,Gujarat Panchayat Service Selection Board (GPSSB),State,Gujarat,Confirmed,Exam cancelled + Arrests-FIR,Exam postponed hours before start after a copy...,19.0,NaN,953000.0,NaN,NaN,Careers360,https://news.careers360.com/gujarat-junior-cle...,High
78,PL-0079,2023-02-25,NDA (May2014-now),REET 2023 (teacher eligibility test),Board of Secondary Education Rajasthan (BSER/R...,State,Rajasthan (Jodhpur),Alleged,Arrests-FIR,Police raided a Jodhpur marriage hall hours be...,37.0,NaN,NaN,NaN,NaN,Free Press Journal,https://www.freepressjournal.in/education/reet...,Medium
79,PL-0080,2023-03-05,NDA (May2014-now),Assistant Engineer (Civil) recruitment exam (a...,Telangana State Public Service Commission (TSPSC),State,Telangana,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),TSPSC confidential-section staff allegedly sto...,12.0,NaN,NaN,NaN,NaN,The South First,https://thesouthfirst.com/news/tspsc-paper-lea...,High
80,PL-0081,2023-03-15,NDA (May2014-now),MP Patwari Recruitment Exam 2023 (Group-2 Sub-...,"Madhya Pradesh Employees Selection Board (ESB,...",State,Madhya Pradesh,Alleged,Probe,"After 30 Jun 2023 results, aspirants and Congr...",NaN,NaN,974000.0,NaN,NaN,The Week,https://www.theweek.in/news/india/2023/07/13/m...,Medium
81,PL-0082,2023-05-11,NDA (May2014-now),CGPSC State Service Examination 2021 (recruitm...,Chhattisgarh Public Service Commission (CGPSC),State,Chhattisgarh,Alleged,Probe (CBI/SIT)+Arrests-FIR,CBI probe into nepotism/favouritism in recruit...,12.0,0.0,129206.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/chhattisgarh...,High
82,PL-0083,2023-05-25,NDA (May2014-now),MP Forest Guard (Vanrakshak) Recruitment Exam ...,Madhya Pradesh Employees Selection Board (ESB),State,Madhya Pradesh,Suspected,Probe,ESB withheld results of 113 candidates after d...,NaN,NaN,100000.0,NaN,NaN,Bansal News,https://bansalnews.com/mp-forest-guard-bharti-...,Low
83,PL-0084,2023-06-03,NDA (May2014-now),AIIMS NORCET-4 (Nursing Officer Recruitment),AIIMS New Delhi,Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),Paper leaked via doctored computer monitors gi...,5.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/delhi/cbi-ar...,High

Number of nda_cases :  (86, 18)

# 13. Filtering UPA Era Paper Leak Cases

In [ ]:
upa_cases = df[df["era"] == "UPA (2004-May2014)"]

display(upa_cases)

print("Number of UPA cases:", upa_cases.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
0,PL-0001,2004-04-11,UPA (2004-May2014),All India Pre-Medical Test (AIPMT/CBSE-PMT) 2004,Central Board of Secondary Education (CBSE),Central,All India,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),Physics and chemistry papers leaked in New Del...,2.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2004/20040412/mai...,High
1,PL-0002,2006-06-01,UPA (2004-May2014),Himachal Pradesh Combined Pre-Medical Test (HP...,Himachal Pradesh University,State,Himachal Pradesh,Confirmed,Retest + Arrests-FIR,HP-CPMT medical entrance paper leaked via a to...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2006/20060831/him...,Medium
2,PL-0003,2008-01-01,UPA (2004-May2014),Vyapam Patwari Recruitment Examination 2008,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Accused produced forged educational certificat...,NaN,10.0,NaN,NaN,NaN,The420.in,https://the420.in/vyapam-scam-cbi-court-patwar...,High
3,PL-0004,2009-07-08,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2009,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Paid solvers/impersonators sat the exam in pla...,NaN,NaN,114.0,NaN,NaN,The Free Press Journal,https://www.freepressjournal.in/education/indo...,High
4,PL-0005,2010-06-06,UPA (2004-May2014),RRB Mumbai 2010 recruitment exam (Assistant Lo...,"Railway Recruitment Board (RRB), Mumbai",Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),CBI registered a case on 15 June 2010 over the...,15.0,10.0,NaN,NaN,NaN,The Week,https://www.theweek.in/wire-updates/national/2...,High
5,PL-0006,2011-01-01,UPA (2004-May2014),Vyapam Contract Teacher Eligibility Test (Samv...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Marks of 84 favoured candidates were inflated ...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
6,PL-0007,2011-02-17,UPA (2004-May2014),CBSE Class 10 & Class 12 Board Examinations 2011,Central Board of Secondary Education (CBSE),Central,Andaman & Nicobar Islands,Confirmed,Retest + Arrests-FIR,Class 12 English/Maths and Class 10 science pa...,3.0,4.0,NaN,NaN,NaN,icbse.com,https://www.icbse.com/news/cbse-question-paper...,High
7,PL-0008,2011-05-01,UPA (2004-May2014),AIEEE (All India Engineering Entrance Examinat...,Central Board of Secondary Education (CBSE),Central,Uttar Pradesh (Kanpur/Lucknow),Confirmed,Retest + Arrests-FIR,Paper found being sold in UP (allegedly for ~R...,1.0,NaN,32000.0,NaN,NaN,icbse.com,https://www.icbse.com/news/aieee-2011-question...,High
8,PL-0009,2011-06-19,UPA (2004-May2014),Chhattisgarh Pre-Medical Test (CG-PMT) 2011,Chhattisgarh Professional Examination Board (C...,State,Chhattisgarh,Confirmed,Exam cancelled + Arrests-FIR,CG-PMT scrapped after a crime-branch raid at a...,12.0,NaN,20000.0,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/chhatis...,High
9,PL-0010,2011-11-13,UPA (2004-May2014),Uttar Pradesh Teacher Eligibility Test (UPTET)...,UP Secondary Education Board / Directorate of ...,State,Uttar Pradesh,Confirmed,Arrests-FIR + Probe (SIT),Marks-manipulation/bribery racket (candidates ...,12.0,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/up-seco...,High
10,PL-0011,2012-01-01,UPA (2004-May2014),MP Food Inspector Selection Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Result/answer-sheet rigging to pass favoured c...,NaN,NaN,NaN,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Low
11,PL-0012,2012-01-01,UPA (2004-May2014),MP Pre-PG (Post-Graduate Medical) Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Vyapam officials supplied photocopied model an...,NaN,NaN,NaN,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Low
12,PL-0013,2012-01-01,UPA (2004-May2014),MP Transport Constable Recruitment Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),OMR sheets were altered by Vyapam employees to...,NaN,NaN,NaN,NaN,NaN,Outlook India,https://www.outlookindia.com/national/india-ne...,Medium
13,PL-0014,2012-01-08,UPA (2004-May2014),AIIMS Post-Graduate (MD/MS) Entrance Examinati...,All India Institute of Medical Sciences (AIIMS),Central,Delhi,Confirmed,Arrests-FIR,Gang photographed the PG entrance paper inside...,7.0,NaN,NaN,NaN,NaN,Careerindia,https://www.careerindia.com/news/2012/01/16/tw...,Medium
14,PL-0015,2012-03-01,UPA (2004-May2014),Karnataka Second PU (Class 12) Board Examinati...,"Dept. of Pre-University Education, Karnataka",State,Karnataka,Confirmed,Arrests-FIR + Probe,"Physics, Maths and Biology papers were stolen ...",10.0,NaN,NaN,NaN,NaN,Careerindia,https://www.careerindia.com/news/2012/04/05/ka...,High
15,PL-0016,2012-06-01,UPA (2004-May2014),Jammu & Kashmir Common Entrance Test (JKCET) 2...,J&K Board of Professional Entrance Examination...,State,Jammu & Kashmir,Confirmed,Arrests-FIR + Probe,Medical entrance papers with answer keys were ...,NaN,11.0,NaN,NaN,NaN,Greater Kashmir,https://www.greaterkashmir.com/kashmir/bopee-s...,High
16,PL-0017,2012-06-01,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Fraud combined impersonation by paid solvers w...,NaN,NaN,286.0,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Medium
17,PL-0018,2012-09-30,UPA (2004-May2014),Vyapam Police Constable Recruitment Examinatio...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Candidates arranged impersonators to sit the 3...,NaN,11.0,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/madhya-pradesh/vya...,High
18,PL-0019,2013-01-01,UPA (2004-May2014),Agricultural Development Officer & combined co...,Assam Public Service Commission (APSC),State,Assam,Confirmed,Arrests-FIR + Probe (CBI/SIT),"""Cash-for-jobs"" scam: OMR sheets altered and m...",NaN,34.0,NaN,NaN,NaN,The Assam Tribune,https://assamtribune.com/assam/rakesh-paul-33-...,High
19,PL-0020,2013-01-01,UPA (2004-May2014),Vyapam Police Constable Recruitment Examinatio...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Impersonation and forgery in the 2013 constabl...,NaN,31.0,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/news/india/2013-po...,High
20,PL-0021,2013-04-21,UPA (2004-May2014),SSC Combined Graduate Level (CGL) Examination ...,Staff Selection Commission (SSC),Central,All India,Confirmed,Retest + Arrests-FIR,Question paper leaked and solved off-site; Del...,9.0,NaN,NaN,NaN,NaN,SSC Portal,https://sscportal.in/news/si-exam-topper-caugh...,High
21,PL-0022,2013-07-07,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2013,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),On the night before the 7 July 2013 exam Indor...,20.0,NaN,NaN,23.0,"SCAM-WIDE, not this single exam: the MP SIT ac...",Careers360,https://news.careers360.com/vyapam-scam-five-s...,High
22,PL-0023,2013-10-26,UPA (2004-May2014),RAS (Rajasthan Administrative Service) Prelimi...,Rajasthan Public Service Commission (RPSC),State,Rajasthan,Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),RAS-2013 prelims (26 Oct 2013) scrapped after ...,NaN,NaN,NaN,1.0,Not an aspirant: the alleged mastermind of the...,Careers360,https://news.careers360.com/rajasthan-ras-pape...,High
23,PL-0024,2014-03-05,UPA (2004-May2014),CBSE Class 12 Physics Board Examination 2014,Central Board of Secondary Education (CBSE),Central,Manipur (Imphal),Confirmed,Exam cancelled + Retest + Arrests-FIR,All three sets of the Class 12 Physics paper w...,NaN,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/latest-...,High

Number of UPA cases: (24, 18)

# 14. Filtering High Confidence Paper Leak Cases

In [ ]:
high_confidence = df[df["confidence"] == "High"]

display(high_confidence)
print("Shape of High Confidence Cases:", high_confidence.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
0,PL-0001,2004-04-11,UPA (2004-May2014),All India Pre-Medical Test (AIPMT/CBSE-PMT) 2004,Central Board of Secondary Education (CBSE),Central,All India,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),Physics and chemistry papers leaked in New Del...,2.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2004/20040412/mai...,High
2,PL-0003,2008-01-01,UPA (2004-May2014),Vyapam Patwari Recruitment Examination 2008,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Accused produced forged educational certificat...,NaN,10.0,NaN,NaN,NaN,The420.in,https://the420.in/vyapam-scam-cbi-court-patwar...,High
3,PL-0004,2009-07-08,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2009,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Paid solvers/impersonators sat the exam in pla...,NaN,NaN,114.0,NaN,NaN,The Free Press Journal,https://www.freepressjournal.in/education/indo...,High
4,PL-0005,2010-06-06,UPA (2004-May2014),RRB Mumbai 2010 recruitment exam (Assistant Lo...,"Railway Recruitment Board (RRB), Mumbai",Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),CBI registered a case on 15 June 2010 over the...,15.0,10.0,NaN,NaN,NaN,The Week,https://www.theweek.in/wire-updates/national/2...,High
5,PL-0006,2011-01-01,UPA (2004-May2014),Vyapam Contract Teacher Eligibility Test (Samv...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Marks of 84 favoured candidates were inflated ...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
6,PL-0007,2011-02-17,UPA (2004-May2014),CBSE Class 10 & Class 12 Board Examinations 2011,Central Board of Secondary Education (CBSE),Central,Andaman & Nicobar Islands,Confirmed,Retest + Arrests-FIR,Class 12 English/Maths and Class 10 science pa...,3.0,4.0,NaN,NaN,NaN,icbse.com,https://www.icbse.com/news/cbse-question-paper...,High
7,PL-0008,2011-05-01,UPA (2004-May2014),AIEEE (All India Engineering Entrance Examinat...,Central Board of Secondary Education (CBSE),Central,Uttar Pradesh (Kanpur/Lucknow),Confirmed,Retest + Arrests-FIR,Paper found being sold in UP (allegedly for ~R...,1.0,NaN,32000.0,NaN,NaN,icbse.com,https://www.icbse.com/news/aieee-2011-question...,High
8,PL-0009,2011-06-19,UPA (2004-May2014),Chhattisgarh Pre-Medical Test (CG-PMT) 2011,Chhattisgarh Professional Examination Board (C...,State,Chhattisgarh,Confirmed,Exam cancelled + Arrests-FIR,CG-PMT scrapped after a crime-branch raid at a...,12.0,NaN,20000.0,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/chhatis...,High
9,PL-0010,2011-11-13,UPA (2004-May2014),Uttar Pradesh Teacher Eligibility Test (UPTET)...,UP Secondary Education Board / Directorate of ...,State,Uttar Pradesh,Confirmed,Arrests-FIR + Probe (SIT),Marks-manipulation/bribery racket (candidates ...,12.0,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/up-seco...,High
14,PL-0015,2012-03-01,UPA (2004-May2014),Karnataka Second PU (Class 12) Board Examinati...,"Dept. of Pre-University Education, Karnataka",State,Karnataka,Confirmed,Arrests-FIR + Probe,"Physics, Maths and Biology papers were stolen ...",10.0,NaN,NaN,NaN,NaN,Careerindia,https://www.careerindia.com/news/2012/04/05/ka...,High
15,PL-0016,2012-06-01,UPA (2004-May2014),Jammu & Kashmir Common Entrance Test (JKCET) 2...,J&K Board of Professional Entrance Examination...,State,Jammu & Kashmir,Confirmed,Arrests-FIR + Probe,Medical entrance papers with answer keys were ...,NaN,11.0,NaN,NaN,NaN,Greater Kashmir,https://www.greaterkashmir.com/kashmir/bopee-s...,High
17,PL-0018,2012-09-30,UPA (2004-May2014),Vyapam Police Constable Recruitment Examinatio...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Candidates arranged impersonators to sit the 3...,NaN,11.0,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/madhya-pradesh/vya...,High
18,PL-0019,2013-01-01,UPA (2004-May2014),Agricultural Development Officer & combined co...,Assam Public Service Commission (APSC),State,Assam,Confirmed,Arrests-FIR + Probe (CBI/SIT),"""Cash-for-jobs"" scam: OMR sheets altered and m...",NaN,34.0,NaN,NaN,NaN,The Assam Tribune,https://assamtribune.com/assam/rakesh-paul-33-...,High
19,PL-0020,2013-01-01,UPA (2004-May2014),Vyapam Police Constable Recruitment Examinatio...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Impersonation and forgery in the 2013 constabl...,NaN,31.0,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/news/india/2013-po...,High
20,PL-0021,2013-04-21,UPA (2004-May2014),SSC Combined Graduate Level (CGL) Examination ...,Staff Selection Commission (SSC),Central,All India,Confirmed,Retest + Arrests-FIR,Question paper leaked and solved off-site; Del...,9.0,NaN,NaN,NaN,NaN,SSC Portal,https://sscportal.in/news/si-exam-topper-caugh...,High
21,PL-0022,2013-07-07,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2013,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),On the night before the 7 July 2013 exam Indor...,20.0,NaN,NaN,23.0,"SCAM-WIDE, not this single exam: the MP SIT ac...",Careers360,https://news.careers360.com/vyapam-scam-five-s...,High
22,PL-0023,2013-10-26,UPA (2004-May2014),RAS (Rajasthan Administrative Service) Prelimi...,Rajasthan Public Service Commission (RPSC),State,Rajasthan,Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),RAS-2013 prelims (26 Oct 2013) scrapped after ...,NaN,NaN,NaN,1.0,Not an aspirant: the alleged mastermind of the...,Careers360,https://news.careers360.com/rajasthan-ras-pape...,High
23,PL-0024,2014-03-05,UPA (2004-May2014),CBSE Class 12 Physics Board Examination 2014,Central Board of Secondary Education (CBSE),Central,Manipur (Imphal),Confirmed,Exam cancelled + Retest + Arrests-FIR,All three sets of the Class 12 Physics paper w...,NaN,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/latest-...,High
25,PL-0026,2015-03-29,NDA (May2014-now),UPPCS Preliminary Examination 2015,Uttar Pradesh Public Service Commission (UPPSC),State,Uttar Pradesh (Lucknow),Confirmed,Exam cancelled+Arrests-FIR,Question paper was photographed about an hour ...,3.0,NaN,450000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
26,PL-0027,2015-05-03,NDA (May2014-now),AIPMT 2015 (All India Pre-Medical Test),CBSE,Central,All India,Confirmed,Exam cancelled + Retest + Arrests-FIR,Bluetooth/micro-SIM answer-key racket intercep...,NaN,NaN,600000.0,NaN,NaN,Republic World,https://www.republicworld.com/education/entran...,High
27,PL-0028,2015-11-14,NDA (May2014-now),HTET Level-3 (Haryana Teacher Eligibility Test),Haryana Board of School Education (HBSE),State,Haryana (Jind),Confirmed,Exam cancelled + Arrests-FIR,Board cancelled the Level-3 exam the same day ...,5.0,NaN,137000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/hary...,High
28,PL-0029,2016-01-01,NDA (May2014-now),State Level Selection Test (SLST) 2016 teacher...,West Bengal School Service Commission (WBSSC),State,West Bengal,Confirmed,Exam cancelled + Probe (CBI/SIT),OMR-sheet manipulation and appointments beyond...,NaN,NaN,25752.0,NaN,NaN,DD News,https://ddnews.gov.in/en/west-bengal-teacher-r...,High
31,PL-0032,2017-02-05,NDA (May2014-now),BSSC 1st Inter-Level Combined (Clerical-grade)...,Bihar Staff Selection Commission (BSSC),State,Bihar (Patna) / Jharkhand (arrest),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),The clerical-grade recruitment paper was leake...,30.0,NaN,NaN,NaN,NaN,The Tribune (PTI),https://www.tribuneindia.com/news/archive/nati...,High
33,PL-0034,2017-07-16,NDA (May2014-now),HCS (Judicial Branch) Preliminary Examination ...,Punjab & Haryana High Court,State,Haryana,Confirmed,Exam cancelled + Arrests-FIR + Probe,A High Court committee found the paper was lea...,NaN,3.0,NaN,NaN,NaN,Careers360,https://news.careers360.com/2017-hcs-exam-pape...,High
35,PL-0036,2017-10-29,NDA (May2014-now),DSSSB Primary Teacher (PRT) Recruitment Exam f...,Delhi Subordinate Services Selection Board (DS...,State,Delhi (NCT of Delhi),Confirmed,Exam cancelled + Retest + Arrests-FIR,Question papers of the PRT exam held on 29 Oct...,NaN,NaN,70000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/delh...,High
36,PL-0037,2018-02-21,NDA (May2014-now),SSC CGL 2017 Tier-II,SSC,Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),Answer key of the 21 Feb 2018 Tier-II paper we...,3.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
37,PL-0038,2018-03-26,NDA (May2014-now),CBSE Class 12 Economics board exam 2018,CBSE,Central,All India,Confirmed,Retest + Arrests-FIR,Question paper photographed and circulated on ...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/cbse-paper-leak-cl...,High
38,PL-0039,2018-03-28,NDA (May2014-now),CBSE Class 10 Mathematics board exam 2018,CBSE,Central,All India,Confirmed,Arrests-FIR,Class 10 Maths paper leaked/circulated before ...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/cbse-paper-leak-cl...,High
42,PL-0043,2019-12-29,NDA (May2014-now),Librarian Grade III recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur/Kota/Ajmer),Confirmed,Exam cancelled + Arrests-FIR,Question paper and answer key circulated on Wh...,6.0,NaN,55000.0,NaN,NaN,Daijiworld,https://daijiworld.com/news/newsDisplay?newsID...,High
43,PL-0044,2020-01-01,NDA (May2014-now),Teacher Eligibility Test (TET) 2020,Maharashtra State Council of Examination (MSCE),State,Maharashtra,Confirmed,Arrests-FIR + Probe (CBI/SIT),Marks of thousands of candidates manipulated f...,13.0,NaN,7800.0,NaN,NaN,Careers360,https://news.careers360.com/tet-case-ias-offic...,High
44,PL-0045,2020-09-20,NDA (May2014-now),Sub-Inspector (unarmed branch) written exam,"State Level Police Recruitment Board (SLPRB), ...",State,Assam,Confirmed,Exam cancelled + Arrests-FIR,Paper circulated on WhatsApp the morning of th...,3.0,NaN,66000.0,NaN,NaN,The Sentinel,https://www.sentinelassam.com/north-east-india...,High
45,PL-0046,2020-10-11,NDA (May2014-now),Medical Officer (Dental) recruitment test,Baba Farid University of Health Sciences (BFUHS),State,"Punjab (leak traced to Goindwal Sahib, Tarn Ta...",Confirmed,Exam cancelled + Retest,Question paper for the dental officer post wen...,NaN,NaN,11000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/1-957...,High
46,PL-0047,2020-12-06,NDA (May2014-now),Junior Engineer (JEN) recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur),Confirmed,Exam cancelled + Arrests-FIR + Retest,Paper leaked from a Jaipur government school a...,24.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-je-recru...,High
47,PL-0048,2021-01-03,NDA (May2014-now),Railway GDCE 2021 (General Departmental Compet...,Railway Recruitment Cell (Western Railway),Central,Gujarat,Confirmed,Arrests-FIR + Probe (CBI/SIT),Candidates allegedly supplied papers with answ...,NaN,NaN,8600.0,NaN,NaN,ThePrint,https://theprint.in/india/railways-exam-paper-...,High
48,PL-0049,2021-01-09,NDA (May2014-now),HSSC Gram Sachiv (Panchayat Secretary) exam,Haryana Staff Selection Commission (HSSC),State,Haryana (Hisar),Confirmed,Exam cancelled + Arrests-FIR,Exams held Jan 9-10 for 697 posts were cancell...,18.0,NaN,800000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/paper...,High
49,PL-0050,2021-02-28,NDA (May2014-now),Army Soldier General Duty Common Entrance Exam...,Indian Army,Central,All India,Confirmed,Exam cancelled + Arrests-FIR,Pan-India recruitment exam cancelled about an ...,3.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/nation/army-...,High
50,PL-0051,2021-07-01,NDA (May2014-now),"Forest Guard, Secretariat Security Guard and a...",Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand,Confirmed,Exam cancelled + Retest,Three UKSSSC exams held in 2021 (graduate-leve...,NaN,NaN,NaN,NaN,NaN,Careers360 (PTI),https://news.careers360.com/uttarakhand-three-...,High
51,PL-0052,2021-08-07,NDA (May2014-now),HSSC Police Constable (Male) recruitment exam,Haryana Staff Selection Commission (HSSC),State,Haryana (Kaithal),Confirmed,Exam cancelled + Arrests-FIR,Written exam cancelled after the paper and ans...,167.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/haryana/four...,High
53,PL-0054,2021-09-13,NDA (May2014-now),Sub-Inspector (SI) recruitment exam 2021,Rajasthan Public Service Commission (RPSC),State,Rajasthan (statewide),Confirmed,Arrests-FIR + Probe (SIT/SOG) + Exam cancelled,Large-scale paper leak involving two RPSC memb...,54.0,NaN,NaN,NaN,NaN,ETV Bharat,https://www.etvbharat.com/en/!state/rajasthan-...,High
54,PL-0055,2021-09-26,NDA (May2014-now),REET 2021 (Rajasthan Eligibility Exam for Teac...,Board of Secondary Education Rajasthan (BSER/R...,State,Rajasthan,Confirmed,Exam cancelled + Arrests-FIR + Retest,Level-2 paper leak led the state to cancel and...,38.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/reet-2021-rajastha...,High
55,PL-0056,2021-10-03,NDA (May2014-now),Police Sub-Inspector (PSI) recruitment exam,Karnataka State Police / Recruitment Wing,State,Karnataka,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),OMR answer sheets tampered to favour candidate...,30.0,NaN,54041.0,NaN,NaN,The Quint,https://www.thequint.com/news/politics/explain...,High
57,PL-0058,2021-11-28,NDA (May2014-now),Uttar Pradesh Teacher Eligibility Test (UPTET)...,UP Examination Regulatory Authority / Basic Ed...,State,Uttar Pradesh (statewide),Confirmed,Exam cancelled+Arrests-FIR,Paper circulated on WhatsApp in several distri...,23.0,NaN,1999000.0,NaN,NaN,India TV News,https://www.indiatvnews.com/education/news-upt...,High
58,PL-0059,2021-12-04,NDA (May2014-now),Graduate-level (Snatak) recruitment exam,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand (Dehradun/Bijnor),Confirmed,Exam cancelled + Arrests-FIR + Probe (STF/SIT),Graduate-level exam for 854 posts across 13 de...,20.0,NaN,NaN,NaN,NaN,ThePrint (PTI),https://theprint.in/india/20-people-arrested-i...,High
59,PL-0060,2021-12-12,NDA (May2014-now),Head Clerk recruitment exam,Gujarat Subordinate Services Selection Board (...,State,Gujarat,Confirmed,Exam cancelled + Arrests-FIR,Question paper obtained from a printing-press ...,14.0,NaN,88000.0,NaN,NaN,Careers360,https://news.careers360.com/guj-exam-for-recru...,High
60,PL-0061,2021-12-12,NDA (May2014-now),MHADA staff recruitment exam,Maharashtra Housing and Area Development Autho...,State,Maharashtra,Confirmed,Exam cancelled + Arrests-FIR,Three held in Pune (including a question-sette...,3.0,NaN,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/education/news-mha...,High
64,PL-0065,2022-03-27,NDA (May2014-now),Himachal Pradesh Police Constable Recruitment ...,Himachal Pradesh Police (state government recr...,State,Himachal Pradesh,Confirmed,Exam cancelled + Retest + Arrests-FIR + Probe ...,"Written test held 27 March 2022 for 1,334 cons...",88.0,NaN,75000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/himachal/cbi...,High
65,PL-0066,2022-04-27,NDA (May2014-now),SSC (Class 10) board examination,Andhra Pradesh Board of Secondary Education / ...,State,Andhra Pradesh,Confirmed,Arrests-FIR,Teachers on exam duty photographed papers minu...,70.0,NaN,NaN,NaN,NaN,Siasat (archive),https://archive.siasat.com/news/andhra-pradesh...,High
66,PL-0067,2022-05-08,NDA (May2014-now),BPSC 67th Combined Competitive Exam (Prelims),Bihar Public Service Commission (BPSC),State,"Bihar (Ara, Bhojpur)",Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),Question paper screenshots went viral on socia...,4.0,NaN,600000.0,NaN,NaN,Careers360,https://news.careers360.com/bpsc-67th-question...,High
67,PL-0068,2022-05-14,NDA (May2014-now),Rajasthan Police Constable recruitment exam,Rajasthan Police Recruitment & Promotion Board,State,Rajasthan (Jaipur/Jhotwara),Confirmed,Exam cancelled + Arrests-FIR + Retest,Second shift paper was leaked via a screenshot...,8.0,NaN,160000.0,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-police-c...,High
68,PL-0069,2022-05-22,NDA (May2014-now),Naib Tehsildar recruitment test (78 posts),Punjab Public Service Commission (PPSC),State,Punjab (Patiala; centres statewide),Confirmed,Arrests-FIR + Exam cancelled,Dummy candidates photographed question papers ...,5.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/5-arr...,High
69,PL-0070,2022-06-01,NDA (May2014-now),Assistant Engineer / Junior Engineer (AE/JE) r...,Uttarakhand Public Service Commission (UKPSC),State,Uttarakhand (Haridwar),Confirmed,Arrests-FIR + Probe (SIT),AE/JE exam held June 2022; an SIT found the qu...,3.0,NaN,NaN,NaN,NaN,Siasat (PTI),https://archive.siasat.com/news/3-arrested-in-...,High
70,PL-0071,2022-07-31,NDA (May2014-now),UPSSSC Lekhpal (Mains) Recruitment Exam 2022,Uttar Pradesh Subordinate Services Selection C...,State,Uttar Pradesh,Alleged,Arrests-FIR,21 people including solvers and impersonators ...,21.0,NaN,250000.0,NaN,NaN,ThePrint,https://theprint.in/india/up-lekhpal-exam-solv...,High
71,PL-0072,2022-08-26,NDA (May2014-now),Assistant Engineer (Civil) exam,Arunachal Pradesh Public Service Commission (A...,State,Arunachal Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),AE (Civil) paper leaked; APPSC secretary and c...,10.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/appsc-examination-...,High
72,PL-0073,2022-11-12,NDA (May2014-now),Forest Guard recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Rajsamand),Confirmed,Exam cancelled + Arrests-FIR,Evening shift cancelled after a paper-leak gan...,9.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-forest-g...,High
74,PL-0075,2022-12-24,NDA (May2014-now),Senior Teacher Grade II (2nd Grade Teacher) Ge...,Rajasthan Public Service Commission (RPSC),State,Rajasthan (Udaipur),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT/ED),Candidates were caught solving the leaked GK p...,44.0,NaN,NaN,NaN,NaN,The Print,https://theprint.in/india/rajasthan-2nd-grade-...,High
75,PL-0076,2022-12-25,NDA (May2014-now),Junior Office Assistant (IT) / JOA (IT) Recrui...,Himachal Pradesh Staff Selection Commission (H...,State,Himachal Pradesh (Hamirpur),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT/CBI),Solved JOA (IT) paper and Rs 2.5 lakh were sei...,6.0,NaN,150000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/himachal/jr-...,High
76,PL-0077,2023-01-08,NDA (May2014-now),Patwari / Lekhpal recruitment exam,Uttarakhand Public Service Commission (UKPSC),State,Uttarakhand (Haridwar),Confirmed,Exam cancelled + Retest + Arrests-FIR,Patwari-Lekhpal exam for 563 posts held 8 Jan ...,5.0,NaN,100000.0,NaN,NaN,Careers360 (PTI),https://news.careers360.com/after-series-of-pa...,High
77,PL-0078,2023-01-29,NDA (May2014-now),GPSSB Junior Clerk recruitment exam,Gujarat Panchayat Service Selection Board (GPSSB),State,Gujarat,Confirmed,Exam cancelled + Arrests-FIR,Exam postponed hours before start after a copy...,19.0,NaN,953000.0,NaN,NaN,Careers360,https://news.careers360.com/gujarat-junior-cle...,High
79,PL-0080,2023-03-05,NDA (May2014-now),Assistant Engineer (Civil) recruitment exam (a...,Telangana State Public Service Commission (TSPSC),State,Telangana,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),TSPSC confidential-section staff allegedly sto...,12.0,NaN,NaN,NaN,NaN,The South First,https://thesouthfirst.com/news/tspsc-paper-lea...,High

Shape of High Confidence Cases: (81, 18)

# 15. Filtering Medium Confidence Paper Leak Cases

In [ ]:
medium_confidence = df[df["confidence"] == "Medium"]

display(medium_confidence)
print("Shape of Medium Confidence Cases:", medium_confidence.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
1,PL-0002,2006-06-01,UPA (2004-May2014),Himachal Pradesh Combined Pre-Medical Test (HP...,Himachal Pradesh University,State,Himachal Pradesh,Confirmed,Retest + Arrests-FIR,HP-CPMT medical entrance paper leaked via a to...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2006/20060831/him...,Medium
12,PL-0013,2012-01-01,UPA (2004-May2014),MP Transport Constable Recruitment Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),OMR sheets were altered by Vyapam employees to...,NaN,NaN,NaN,NaN,NaN,Outlook India,https://www.outlookindia.com/national/india-ne...,Medium
13,PL-0014,2012-01-08,UPA (2004-May2014),AIIMS Post-Graduate (MD/MS) Entrance Examinati...,All India Institute of Medical Sciences (AIIMS),Central,Delhi,Confirmed,Arrests-FIR,Gang photographed the PG entrance paper inside...,7.0,NaN,NaN,NaN,NaN,Careerindia,https://www.careerindia.com/news/2012/01/16/tw...,Medium
16,PL-0017,2012-06-01,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Fraud combined impersonation by paid solvers w...,NaN,NaN,286.0,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Medium
24,PL-0025,2014-06-29,NDA (May2014-now),"DSSSB Head Clerk (Grade II DASS, Post Code 90/...",Delhi Subordinate Services Selection Board (DS...,State,Delhi (NCT of Delhi),Alleged,Exam cancelled + Probe,Complaints (Oct 2014-Mar 2015) alleged leakage...,NaN,NaN,NaN,NaN,NaN,SCC Online (Supreme Court judgment coverage),https://www.scconline.com/blog/post/2021/03/05...,Medium
29,PL-0030,2016-03-06,NDA (May2014-now),Village Panchayat Development Officer (VPDO/VD...,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand,Confirmed,Exam cancelled + Probe (ED/PMLA) + Arrests-FIR,VPDO exam held 6 Mar 2016 was cancelled on 1 D...,17.0,NaN,NaN,NaN,NaN,Prokerala (PTI),https://www.prokerala.com/news/articles/a15886...,Medium
30,PL-0031,2016-05-01,NDA (May2014-now),NEET-UG 2016 (Phase II),CBSE,Central,All India,Denied,None reported,Inter-state leak allegations around the 2016 N...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
32,PL-0033,2017-05-07,NDA (May2014-now),NEET-UG 2017,CBSE,Central,All India,Alleged,Arrests-FIR,Uttarakhand/Bihar inter-state racket promised ...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
34,PL-0035,2017-07-24,NDA (May2014-now),UP Police Inspector (Sub-Inspector/Inspector) ...,UP Police Recruitment and Promotion Board (UPP...,State,Uttar Pradesh,Confirmed,Exam cancelled+Probe (STF),"The online recruitment test for 3,307 inspecto...",NaN,NaN,120000.0,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
39,PL-0040,2018-03-31,NDA (May2014-now),UPPCL Junior Engineer / Technician online recr...,Uttar Pradesh Power Corporation Ltd (UPPCL),State,Uttar Pradesh,Confirmed,Exam cancelled+Probe (SIT/STF),UPPCL nullified its 2018 online recruitment ex...,NaN,NaN,NaN,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
40,PL-0041,2018-09-02,NDA (May2014-now),UPSSSC Tubewell Operator (Nalkoop Chalak) Recr...,Uttar Pradesh Subordinate Services Selection C...,State,Uttar Pradesh (Meerut),Confirmed,Exam cancelled+Arrests-FIR,The Hindi question paper leaked and was sold f...,11.0,NaN,250000.0,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
41,PL-0042,2019-11-17,NDA (May2014-now),Non-Secretariat Clerk recruitment exam,Gujarat Subordinate Services Selection Board (...,State,Gujarat,Confirmed,Exam cancelled,Clerk exam cancelled in December 2019 after al...,NaN,NaN,NaN,NaN,NaN,The Federal,https://thefederal.com/states/west/gujarat/aft...,Medium
52,PL-0053,2021-09-12,NDA (May2014-now),NEET-UG 2021,NTA,Central,All India,Confirmed,Arrests-FIR,Invigilator and solver-gang involvement with l...,NaN,NaN,NaN,NaN,NaN,Careers360 (NEET leak history),https://medicine.careers360.com/articles/how-m...,Medium
56,PL-0057,2021-10-23,NDA (May2014-now),Patwari (village revenue officer) recruitment ...,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur/Dausa),Alleged,Arrests-FIR,A coaching-institute owner was arrested for se...,2.0,NaN,1562000.0,NaN,NaN,Careers360,https://news.careers360.com/patwari-exam-coach...,Medium
61,PL-0062,2022-02-13,NDA (May2014-now),Class 10 Science & Class 12 Maths revision exams,Tamil Nadu School Education Department,State,Tamil Nadu (Tiruvannamalai),Confirmed,None reported,Papers from two private schools photographed a...,NaN,NaN,NaN,NaN,NaN,The News Minute,https://www.thenewsminute.com/article/tn-revis...,Medium
62,PL-0063,2022-03-01,NDA (May2014-now),Lower Division Clerk (LDC) recruitment exam,Rajasthan High Court,State,Rajasthan (Jodhpur),Confirmed,Exam cancelled,The High Court's LDC recruitment paper was lea...,NaN,NaN,NaN,NaN,NaN,Daijiworld,https://daijiworld.com/news/newsDisplay?newsID...,Medium
63,PL-0064,2022-03-27,NDA (May2014-now),Forest Guard recruitment exam,Gujarat University / State Forest Department,State,Gujarat,Alleged,Arrests-FIR,A candidate in Mehsana was found with a full a...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/gujarat-forest-gua...,Medium
73,PL-0074,2022-12-23,NDA (May2014-now),BSSC 3rd Graduate Level (CGL) Combined Competi...,Bihar Staff Selection Commission (BSSC),State,"Bihar (528 centres, 38 districts)",Confirmed,Exam cancelled + Probe (SIT),Pages of the first-shift question paper (for 2...,NaN,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/bssc-cgl-question-...,Medium
78,PL-0079,2023-02-25,NDA (May2014-now),REET 2023 (teacher eligibility test),Board of Secondary Education Rajasthan (BSER/R...,State,Rajasthan (Jodhpur),Alleged,Arrests-FIR,Police raided a Jodhpur marriage hall hours be...,37.0,NaN,NaN,NaN,NaN,Free Press Journal,https://www.freepressjournal.in/education/reet...,Medium
80,PL-0081,2023-03-15,NDA (May2014-now),MP Patwari Recruitment Exam 2023 (Group-2 Sub-...,"Madhya Pradesh Employees Selection Board (ESB,...",State,Madhya Pradesh,Alleged,Probe,"After 30 Jun 2023 results, aspirants and Congr...",NaN,NaN,974000.0,NaN,NaN,The Week,https://www.theweek.in/news/india/2023/07/13/m...,Medium
85,PL-0086,2023-08-17,NDA (May2014-now),Talathi (village accountant) recruitment exam,Maharashtra Revenue Dept / TCS-ION (conducting...,State,Maharashtra,Alleged,Arrests-FIR,A repeat paper-leak suspect caught in Nashik o...,NaN,NaN,865000.0,NaN,NaN,Lokmat Times,https://www.lokmattimes.com/maharashtra/leaks-...,Medium
95,PL-0096,2024-06-23,NDA (May2014-now),NEET-PG 2024,NBEMS,Central,All India,Suspected,None reported,Postponed ~12 hours before the exam as a preca...,NaN,NaN,240000.0,NaN,NaN,Medical Dialogues,https://medicaldialogues.in/news/education/nee...,Medium
103,PL-0104,2025-12-21,NDA (May2014-now),Group-B recruitment exam (408 posts incl Naib ...,Punjab Subordinate Services Selection Board (P...,State,Punjab (Bathinda highlighted),Suspected,Probe (SIT/VB),Aspirants alleged irregularities (answer-sheet...,NaN,NaN,100000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/bathinda/six...,Medium
104,PL-0105,2026-02-26,NDA (May2014-now),Class 12 Chemistry board examination,Maharashtra State Board of Secondary & Higher ...,State,Maharashtra (Nagpur),Confirmed,Arrests-FIR + Probe (CBI/SIT),Coaching-academy practice-test questions match...,1.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/maharashtra-board-...,Medium
105,PL-0106,2026-03-14,NDA (May2014-now),CGBSE Class 12 Hindi Board Examination 2026,Chhattisgarh Board of Secondary Education (CGBSE),State,Chhattisgarh,Confirmed,Exam cancelled+Retest+Arrests-FIR,Class 12 Hindi paper leaked and circulated on ...,3.0,0.0,NaN,NaN,NaN,Careers360,https://news.careers360.com/chhattisgarh-board...,Medium
108,PL-0109,2026-07-04,NDA (May2014-now),HTET Level-3 / PGT (Haryana Teacher Eligibilit...,Haryana Board of School Education (HBSE),State,Haryana,Alleged,None reported,Congress alleged a paper leak with broken seal...,NaN,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/haryana/hary...,Medium

Shape of Medium Confidence Cases: (26, 18)

# 16. Filtering Low Confidence Paper Leak Cases

In [ ]:
low_confidence = df[df["confidence"] == "Low"]

display(low_confidence)
print("Shape of Low Confidence Cases:", low_confidence.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
10,PL-0011,2012-01-01,UPA (2004-May2014),MP Food Inspector Selection Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Result/answer-sheet rigging to pass favoured c...,NaN,NaN,NaN,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Low
11,PL-0012,2012-01-01,UPA (2004-May2014),MP Pre-PG (Post-Graduate Medical) Test 2012,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Vyapam officials supplied photocopied model an...,NaN,NaN,NaN,NaN,NaN,Wikipedia,https://en.wikipedia.org/wiki/Vyapam_scam,Low
82,PL-0083,2023-05-25,NDA (May2014-now),MP Forest Guard (Vanrakshak) Recruitment Exam ...,Madhya Pradesh Employees Selection Board (ESB),State,Madhya Pradesh,Suspected,Probe,ESB withheld results of 113 candidates after d...,NaN,NaN,100000.0,NaN,NaN,Bansal News,https://bansalnews.com/mp-forest-guard-bharti-...,Low

Shape of Low Confidence Cases: (3, 18)

# **Filtering Cases with Arrest Information**

In [ ]:
arrest_cases = df[df["arrests"].notna()]

display(arrest_cases)
print("Shape of Arrest Cases:", arrest_cases.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
0,PL-0001,2004-04-11,UPA (2004-May2014),All India Pre-Medical Test (AIPMT/CBSE-PMT) 2004,Central Board of Secondary Education (CBSE),Central,All India,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),Physics and chemistry papers leaked in New Del...,2.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/2004/20040412/mai...,High
4,PL-0005,2010-06-06,UPA (2004-May2014),RRB Mumbai 2010 recruitment exam (Assistant Lo...,"Railway Recruitment Board (RRB), Mumbai",Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),CBI registered a case on 15 June 2010 over the...,15.0,10.0,NaN,NaN,NaN,The Week,https://www.theweek.in/wire-updates/national/2...,High
6,PL-0007,2011-02-17,UPA (2004-May2014),CBSE Class 10 & Class 12 Board Examinations 2011,Central Board of Secondary Education (CBSE),Central,Andaman & Nicobar Islands,Confirmed,Retest + Arrests-FIR,Class 12 English/Maths and Class 10 science pa...,3.0,4.0,NaN,NaN,NaN,icbse.com,https://www.icbse.com/news/cbse-question-paper...,High
7,PL-0008,2011-05-01,UPA (2004-May2014),AIEEE (All India Engineering Entrance Examinat...,Central Board of Secondary Education (CBSE),Central,Uttar Pradesh (Kanpur/Lucknow),Confirmed,Retest + Arrests-FIR,Paper found being sold in UP (allegedly for ~R...,1.0,NaN,32000.0,NaN,NaN,icbse.com,https://www.icbse.com/news/aieee-2011-question...,High
8,PL-0009,2011-06-19,UPA (2004-May2014),Chhattisgarh Pre-Medical Test (CG-PMT) 2011,Chhattisgarh Professional Examination Board (C...,State,Chhattisgarh,Confirmed,Exam cancelled + Arrests-FIR,CG-PMT scrapped after a crime-branch raid at a...,12.0,NaN,20000.0,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/chhatis...,High
9,PL-0010,2011-11-13,UPA (2004-May2014),Uttar Pradesh Teacher Eligibility Test (UPTET)...,UP Secondary Education Board / Directorate of ...,State,Uttar Pradesh,Confirmed,Arrests-FIR + Probe (SIT),Marks-manipulation/bribery racket (candidates ...,12.0,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/up-seco...,High
13,PL-0014,2012-01-08,UPA (2004-May2014),AIIMS Post-Graduate (MD/MS) Entrance Examinati...,All India Institute of Medical Sciences (AIIMS),Central,Delhi,Confirmed,Arrests-FIR,Gang photographed the PG entrance paper inside...,7.0,NaN,NaN,NaN,NaN,Careerindia,https://www.careerindia.com/news/2012/01/16/tw...,Medium
14,PL-0015,2012-03-01,UPA (2004-May2014),Karnataka Second PU (Class 12) Board Examinati...,"Dept. of Pre-University Education, Karnataka",State,Karnataka,Confirmed,Arrests-FIR + Probe,"Physics, Maths and Biology papers were stolen ...",10.0,NaN,NaN,NaN,NaN,Careerindia,https://www.careerindia.com/news/2012/04/05/ka...,High
20,PL-0021,2013-04-21,UPA (2004-May2014),SSC Combined Graduate Level (CGL) Examination ...,Staff Selection Commission (SSC),Central,All India,Confirmed,Retest + Arrests-FIR,Question paper leaked and solved off-site; Del...,9.0,NaN,NaN,NaN,NaN,SSC Portal,https://sscportal.in/news/si-exam-topper-caugh...,High
21,PL-0022,2013-07-07,UPA (2004-May2014),MP Pre-Medical Test (PMT) 2013,Vyapam (MPPEB),State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),On the night before the 7 July 2013 exam Indor...,20.0,NaN,NaN,23.0,"SCAM-WIDE, not this single exam: the MP SIT ac...",Careers360,https://news.careers360.com/vyapam-scam-five-s...,High
25,PL-0026,2015-03-29,NDA (May2014-now),UPPCS Preliminary Examination 2015,Uttar Pradesh Public Service Commission (UPPSC),State,Uttar Pradesh (Lucknow),Confirmed,Exam cancelled+Arrests-FIR,Question paper was photographed about an hour ...,3.0,NaN,450000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
27,PL-0028,2015-11-14,NDA (May2014-now),HTET Level-3 (Haryana Teacher Eligibility Test),Haryana Board of School Education (HBSE),State,Haryana (Jind),Confirmed,Exam cancelled + Arrests-FIR,Board cancelled the Level-3 exam the same day ...,5.0,NaN,137000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/hary...,High
29,PL-0030,2016-03-06,NDA (May2014-now),Village Panchayat Development Officer (VPDO/VD...,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand,Confirmed,Exam cancelled + Probe (ED/PMLA) + Arrests-FIR,VPDO exam held 6 Mar 2016 was cancelled on 1 D...,17.0,NaN,NaN,NaN,NaN,Prokerala (PTI),https://www.prokerala.com/news/articles/a15886...,Medium
31,PL-0032,2017-02-05,NDA (May2014-now),BSSC 1st Inter-Level Combined (Clerical-grade)...,Bihar Staff Selection Commission (BSSC),State,Bihar (Patna) / Jharkhand (arrest),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),The clerical-grade recruitment paper was leake...,30.0,NaN,NaN,NaN,NaN,The Tribune (PTI),https://www.tribuneindia.com/news/archive/nati...,High
36,PL-0037,2018-02-21,NDA (May2014-now),SSC CGL 2017 Tier-II,SSC,Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),Answer key of the 21 Feb 2018 Tier-II paper we...,3.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/archive/nati...,High
40,PL-0041,2018-09-02,NDA (May2014-now),UPSSSC Tubewell Operator (Nalkoop Chalak) Recr...,Uttar Pradesh Subordinate Services Selection C...,State,Uttar Pradesh (Meerut),Confirmed,Exam cancelled+Arrests-FIR,The Hindi question paper leaked and was sold f...,11.0,NaN,250000.0,NaN,NaN,Ground Report,https://www.groundreport.in/education/how-many...,Medium
42,PL-0043,2019-12-29,NDA (May2014-now),Librarian Grade III recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur/Kota/Ajmer),Confirmed,Exam cancelled + Arrests-FIR,Question paper and answer key circulated on Wh...,6.0,NaN,55000.0,NaN,NaN,Daijiworld,https://daijiworld.com/news/newsDisplay?newsID...,High
43,PL-0044,2020-01-01,NDA (May2014-now),Teacher Eligibility Test (TET) 2020,Maharashtra State Council of Examination (MSCE),State,Maharashtra,Confirmed,Arrests-FIR + Probe (CBI/SIT),Marks of thousands of candidates manipulated f...,13.0,NaN,7800.0,NaN,NaN,Careers360,https://news.careers360.com/tet-case-ias-offic...,High
44,PL-0045,2020-09-20,NDA (May2014-now),Sub-Inspector (unarmed branch) written exam,"State Level Police Recruitment Board (SLPRB), ...",State,Assam,Confirmed,Exam cancelled + Arrests-FIR,Paper circulated on WhatsApp the morning of th...,3.0,NaN,66000.0,NaN,NaN,The Sentinel,https://www.sentinelassam.com/north-east-india...,High
46,PL-0047,2020-12-06,NDA (May2014-now),Junior Engineer (JEN) recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur),Confirmed,Exam cancelled + Arrests-FIR + Retest,Paper leaked from a Jaipur government school a...,24.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-je-recru...,High
48,PL-0049,2021-01-09,NDA (May2014-now),HSSC Gram Sachiv (Panchayat Secretary) exam,Haryana Staff Selection Commission (HSSC),State,Haryana (Hisar),Confirmed,Exam cancelled + Arrests-FIR,Exams held Jan 9-10 for 697 posts were cancell...,18.0,NaN,800000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/paper...,High
49,PL-0050,2021-02-28,NDA (May2014-now),Army Soldier General Duty Common Entrance Exam...,Indian Army,Central,All India,Confirmed,Exam cancelled + Arrests-FIR,Pan-India recruitment exam cancelled about an ...,3.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/nation/army-...,High
51,PL-0052,2021-08-07,NDA (May2014-now),HSSC Police Constable (Male) recruitment exam,Haryana Staff Selection Commission (HSSC),State,Haryana (Kaithal),Confirmed,Exam cancelled + Arrests-FIR,Written exam cancelled after the paper and ans...,167.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/haryana/four...,High
53,PL-0054,2021-09-13,NDA (May2014-now),Sub-Inspector (SI) recruitment exam 2021,Rajasthan Public Service Commission (RPSC),State,Rajasthan (statewide),Confirmed,Arrests-FIR + Probe (SIT/SOG) + Exam cancelled,Large-scale paper leak involving two RPSC memb...,54.0,NaN,NaN,NaN,NaN,ETV Bharat,https://www.etvbharat.com/en/!state/rajasthan-...,High
54,PL-0055,2021-09-26,NDA (May2014-now),REET 2021 (Rajasthan Eligibility Exam for Teac...,Board of Secondary Education Rajasthan (BSER/R...,State,Rajasthan,Confirmed,Exam cancelled + Arrests-FIR + Retest,Level-2 paper leak led the state to cancel and...,38.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/reet-2021-rajastha...,High
55,PL-0056,2021-10-03,NDA (May2014-now),Police Sub-Inspector (PSI) recruitment exam,Karnataka State Police / Recruitment Wing,State,Karnataka,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),OMR answer sheets tampered to favour candidate...,30.0,NaN,54041.0,NaN,NaN,The Quint,https://www.thequint.com/news/politics/explain...,High
56,PL-0057,2021-10-23,NDA (May2014-now),Patwari (village revenue officer) recruitment ...,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Jaipur/Dausa),Alleged,Arrests-FIR,A coaching-institute owner was arrested for se...,2.0,NaN,1562000.0,NaN,NaN,Careers360,https://news.careers360.com/patwari-exam-coach...,Medium
57,PL-0058,2021-11-28,NDA (May2014-now),Uttar Pradesh Teacher Eligibility Test (UPTET)...,UP Examination Regulatory Authority / Basic Ed...,State,Uttar Pradesh (statewide),Confirmed,Exam cancelled+Arrests-FIR,Paper circulated on WhatsApp in several distri...,23.0,NaN,1999000.0,NaN,NaN,India TV News,https://www.indiatvnews.com/education/news-upt...,High
58,PL-0059,2021-12-04,NDA (May2014-now),Graduate-level (Snatak) recruitment exam,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand (Dehradun/Bijnor),Confirmed,Exam cancelled + Arrests-FIR + Probe (STF/SIT),Graduate-level exam for 854 posts across 13 de...,20.0,NaN,NaN,NaN,NaN,ThePrint (PTI),https://theprint.in/india/20-people-arrested-i...,High
59,PL-0060,2021-12-12,NDA (May2014-now),Head Clerk recruitment exam,Gujarat Subordinate Services Selection Board (...,State,Gujarat,Confirmed,Exam cancelled + Arrests-FIR,Question paper obtained from a printing-press ...,14.0,NaN,88000.0,NaN,NaN,Careers360,https://news.careers360.com/guj-exam-for-recru...,High
60,PL-0061,2021-12-12,NDA (May2014-now),MHADA staff recruitment exam,Maharashtra Housing and Area Development Autho...,State,Maharashtra,Confirmed,Exam cancelled + Arrests-FIR,Three held in Pune (including a question-sette...,3.0,NaN,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/education/news-mha...,High
64,PL-0065,2022-03-27,NDA (May2014-now),Himachal Pradesh Police Constable Recruitment ...,Himachal Pradesh Police (state government recr...,State,Himachal Pradesh,Confirmed,Exam cancelled + Retest + Arrests-FIR + Probe ...,"Written test held 27 March 2022 for 1,334 cons...",88.0,NaN,75000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/himachal/cbi...,High
65,PL-0066,2022-04-27,NDA (May2014-now),SSC (Class 10) board examination,Andhra Pradesh Board of Secondary Education / ...,State,Andhra Pradesh,Confirmed,Arrests-FIR,Teachers on exam duty photographed papers minu...,70.0,NaN,NaN,NaN,NaN,Siasat (archive),https://archive.siasat.com/news/andhra-pradesh...,High
66,PL-0067,2022-05-08,NDA (May2014-now),BPSC 67th Combined Competitive Exam (Prelims),Bihar Public Service Commission (BPSC),State,"Bihar (Ara, Bhojpur)",Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),Question paper screenshots went viral on socia...,4.0,NaN,600000.0,NaN,NaN,Careers360,https://news.careers360.com/bpsc-67th-question...,High
67,PL-0068,2022-05-14,NDA (May2014-now),Rajasthan Police Constable recruitment exam,Rajasthan Police Recruitment & Promotion Board,State,Rajasthan (Jaipur/Jhotwara),Confirmed,Exam cancelled + Arrests-FIR + Retest,Second shift paper was leaked via a screenshot...,8.0,NaN,160000.0,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-police-c...,High
68,PL-0069,2022-05-22,NDA (May2014-now),Naib Tehsildar recruitment test (78 posts),Punjab Public Service Commission (PPSC),State,Punjab (Patiala; centres statewide),Confirmed,Arrests-FIR + Exam cancelled,Dummy candidates photographed question papers ...,5.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/punjab/5-arr...,High
69,PL-0070,2022-06-01,NDA (May2014-now),Assistant Engineer / Junior Engineer (AE/JE) r...,Uttarakhand Public Service Commission (UKPSC),State,Uttarakhand (Haridwar),Confirmed,Arrests-FIR + Probe (SIT),AE/JE exam held June 2022; an SIT found the qu...,3.0,NaN,NaN,NaN,NaN,Siasat (PTI),https://archive.siasat.com/news/3-arrested-in-...,High
70,PL-0071,2022-07-31,NDA (May2014-now),UPSSSC Lekhpal (Mains) Recruitment Exam 2022,Uttar Pradesh Subordinate Services Selection C...,State,Uttar Pradesh,Alleged,Arrests-FIR,21 people including solvers and impersonators ...,21.0,NaN,250000.0,NaN,NaN,ThePrint,https://theprint.in/india/up-lekhpal-exam-solv...,High
71,PL-0072,2022-08-26,NDA (May2014-now),Assistant Engineer (Civil) exam,Arunachal Pradesh Public Service Commission (A...,State,Arunachal Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),AE (Civil) paper leaked; APPSC secretary and c...,10.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/appsc-examination-...,High
72,PL-0073,2022-11-12,NDA (May2014-now),Forest Guard recruitment exam,Rajasthan Staff Selection Board (RSMSSB),State,Rajasthan (Rajsamand),Confirmed,Exam cancelled + Arrests-FIR,Evening shift cancelled after a paper-leak gan...,9.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/rajasthan-forest-g...,High
74,PL-0075,2022-12-24,NDA (May2014-now),Senior Teacher Grade II (2nd Grade Teacher) Ge...,Rajasthan Public Service Commission (RPSC),State,Rajasthan (Udaipur),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT/ED),Candidates were caught solving the leaked GK p...,44.0,NaN,NaN,NaN,NaN,The Print,https://theprint.in/india/rajasthan-2nd-grade-...,High
75,PL-0076,2022-12-25,NDA (May2014-now),Junior Office Assistant (IT) / JOA (IT) Recrui...,Himachal Pradesh Staff Selection Commission (H...,State,Himachal Pradesh (Hamirpur),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT/CBI),Solved JOA (IT) paper and Rs 2.5 lakh were sei...,6.0,NaN,150000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/himachal/jr-...,High
76,PL-0077,2023-01-08,NDA (May2014-now),Patwari / Lekhpal recruitment exam,Uttarakhand Public Service Commission (UKPSC),State,Uttarakhand (Haridwar),Confirmed,Exam cancelled + Retest + Arrests-FIR,Patwari-Lekhpal exam for 563 posts held 8 Jan ...,5.0,NaN,100000.0,NaN,NaN,Careers360 (PTI),https://news.careers360.com/after-series-of-pa...,High
77,PL-0078,2023-01-29,NDA (May2014-now),GPSSB Junior Clerk recruitment exam,Gujarat Panchayat Service Selection Board (GPSSB),State,Gujarat,Confirmed,Exam cancelled + Arrests-FIR,Exam postponed hours before start after a copy...,19.0,NaN,953000.0,NaN,NaN,Careers360,https://news.careers360.com/gujarat-junior-cle...,High
78,PL-0079,2023-02-25,NDA (May2014-now),REET 2023 (teacher eligibility test),Board of Secondary Education Rajasthan (BSER/R...,State,Rajasthan (Jodhpur),Alleged,Arrests-FIR,Police raided a Jodhpur marriage hall hours be...,37.0,NaN,NaN,NaN,NaN,Free Press Journal,https://www.freepressjournal.in/education/reet...,Medium
79,PL-0080,2023-03-05,NDA (May2014-now),Assistant Engineer (Civil) recruitment exam (a...,Telangana State Public Service Commission (TSPSC),State,Telangana,Confirmed,Exam cancelled + Arrests-FIR + Probe (CBI/SIT),TSPSC confidential-section staff allegedly sto...,12.0,NaN,NaN,NaN,NaN,The South First,https://thesouthfirst.com/news/tspsc-paper-lea...,High
81,PL-0082,2023-05-11,NDA (May2014-now),CGPSC State Service Examination 2021 (recruitm...,Chhattisgarh Public Service Commission (CGPSC),State,Chhattisgarh,Alleged,Probe (CBI/SIT)+Arrests-FIR,CBI probe into nepotism/favouritism in recruit...,12.0,0.0,129206.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/chhattisgarh...,High
83,PL-0084,2023-06-03,NDA (May2014-now),AIIMS NORCET-4 (Nursing Officer Recruitment),AIIMS New Delhi,Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),Paper leaked via doctored computer monitors gi...,5.0,NaN,NaN,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/delhi/cbi-ar...,High
84,PL-0085,2023-07-16,NDA (May2014-now),Junior Engineer (Civil) main written exam (Com...,Odisha Staff Selection Commission (OSSC),State,Odisha,Confirmed,Exam cancelled + Arrests-FIR,Seized papers matched the original; police con...,17.0,NaN,NaN,NaN,NaN,Outlook India,https://www.outlookindia.com/education/ossc-ca...,High
86,PL-0087,2023-10-01,NDA (May2014-now),Bihar Police Constable Recruitment Written Exam,Central Selection Board of Constable (CSBC),State,Bihar (37 districts),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),CSBC cancelled the Oct 1 constable exam (for 2...,148.0,NaN,NaN,NaN,NaN,The Week (PTI),https://www.theweek.in/wire-updates/national/2...,High
89,PL-0090,2024-02-17,NDA (May2014-now),UP Police Constable Recruitment Exam 2024,UP Police Recruitment and Promotion Board (UPP...,State,Uttar Pradesh (statewide),Confirmed,Exam cancelled+Retest+Arrests-FIR+Probe (STF),"The 17-18 Feb 2024 exam for 60,244 posts (over...",54.0,NaN,4800000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/uttar-prades...,High
90,PL-0091,2024-03-15,NDA (May2014-now),BPSC TRE 3.0 School Teacher Recruitment Exam,Bihar Public Service Commission (BPSC),State,Bihar (statewide),Confirmed,Exam cancelled + Retest + Arrests-FIR + Probe ...,EOU found a solver gang obtained the paper bef...,266.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/bpsc-tre-30-exam-c...,High
93,PL-0094,2024-06-18,NDA (May2014-now),UGC-NET June 2024,NTA,Central,All India,Denied,Exam cancelled + Probe (CBI/SIT),Education Ministry cancelled the exam a day af...,0.0,NaN,900000.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/india/cbi-cl...,High
96,PL-0097,2024-09-21,NDA (May2014-now),JSSC CGL / JGGLCCE (re-conducted exam),Jharkhand Staff Selection Commission (JSSC),State,Jharkhand,Alleged,Arrests-FIR+Probe (CBI/SIT),Paper-leak allegations dogged the re-held CGL ...,10.0,NaN,304769.0,NaN,NaN,ThePrint,https://theprint.in/india/5-irb-jawans-among-8...,High
97,PL-0098,2024-12-01,NDA (May2014-now),NHM Bihar Community Health Officer (CHO) Recru...,State Health Society (SHS)/NHM Bihar,State,Bihar (Patna and other centres),Confirmed,Exam cancelled + Arrests-FIR + Probe (SIT),"The computer-based CHO exam (for ~4,500 posts)...",37.0,NaN,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/jobs/news/nhm-biha...,High
99,PL-0100,2025-03-04,NDA (May2014-now),East Central Railway departmental promotion ex...,East Central Railway / Railway Board,Central,Uttar Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT) + Exam cancelled,CBI arrested 26 ECR officials at Mughal Sarai ...,26.0,NaN,NaN,NaN,NaN,India TV News,https://www.indiatvnews.com/news/india/railway...,High
100,PL-0101,2025-04-16,NDA (May2014-now),UPESSC Assistant Professor Recruitment Exam 2025,Uttar Pradesh Education Service Selection Comm...,State,Uttar Pradesh,Confirmed,Exam cancelled+Arrests-FIR+Probe (STF),"The 16-17 Apr 2025 exam (1,017 posts, ~1.14 la...",3.0,NaN,114000.0,NaN,NaN,Careers360,https://news.careers360.com/upessc-assistant-p...,High
101,PL-0102,2025-09-21,NDA (May2014-now),Graduate-level recruitment exam,Uttarakhand Subordinate Service Selection Comm...,State,Uttarakhand (Haridwar),Confirmed,Exam cancelled + Retest + Arrests-FIR + Probe ...,Graduate-level exam for 416 posts held 21 Sep ...,2.0,NaN,100000.0,NaN,NaN,The Tribune (PTI),https://www.tribuneindia.com/news/examcancelle...,High
102,PL-0103,2025-11-23,NDA (May2014-now),Teacher Eligibility Test (TET),Maharashtra State Council of Examination (MSCE),State,Maharashtra,Confirmed,Arrests-FIR + Probe (CBI/SIT),Kolhapur police busted a ring selling leaked T...,18.0,NaN,NaN,NaN,NaN,Careers360,https://news.careers360.com/maharashtra-tet-pa...,High

Shape of Arrest Cases: (63, 18)

# **Filtering Cases with Conviction Information**

In [ ]:
conviction_cases = df[df["convictions"].notna()]

display(conviction_cases)
print("Shape of Conviction Cases:", conviction_cases.shape)

,incident_id,date,era,exam_name,conducting_body,body_type,area,leak_status,action_taken,note,arrests,convictions,aspirants_affected,linked_deaths,deaths_note,source_name,source_url,confidence
2,PL-0003,2008-01-01,UPA (2004-May2014),Vyapam Patwari Recruitment Examination 2008,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Accused produced forged educational certificat...,NaN,10.0,NaN,NaN,NaN,The420.in,https://the420.in/vyapam-scam-cbi-court-patwar...,High
4,PL-0005,2010-06-06,UPA (2004-May2014),RRB Mumbai 2010 recruitment exam (Assistant Lo...,"Railway Recruitment Board (RRB), Mumbai",Central,All India,Confirmed,Arrests-FIR + Probe (CBI/SIT),CBI registered a case on 15 June 2010 over the...,15.0,10.0,NaN,NaN,NaN,The Week,https://www.theweek.in/wire-updates/national/2...,High
6,PL-0007,2011-02-17,UPA (2004-May2014),CBSE Class 10 & Class 12 Board Examinations 2011,Central Board of Secondary Education (CBSE),Central,Andaman & Nicobar Islands,Confirmed,Retest + Arrests-FIR,Class 12 English/Maths and Class 10 science pa...,3.0,4.0,NaN,NaN,NaN,icbse.com,https://www.icbse.com/news/cbse-question-paper...,High
15,PL-0016,2012-06-01,UPA (2004-May2014),Jammu & Kashmir Common Entrance Test (JKCET) 2...,J&K Board of Professional Entrance Examination...,State,Jammu & Kashmir,Confirmed,Arrests-FIR + Probe,Medical entrance papers with answer keys were ...,NaN,11.0,NaN,NaN,NaN,Greater Kashmir,https://www.greaterkashmir.com/kashmir/bopee-s...,High
17,PL-0018,2012-09-30,UPA (2004-May2014),Vyapam Police Constable Recruitment Examinatio...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Candidates arranged impersonators to sit the 3...,NaN,11.0,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/madhya-pradesh/vya...,High
18,PL-0019,2013-01-01,UPA (2004-May2014),Agricultural Development Officer & combined co...,Assam Public Service Commission (APSC),State,Assam,Confirmed,Arrests-FIR + Probe (CBI/SIT),"""Cash-for-jobs"" scam: OMR sheets altered and m...",NaN,34.0,NaN,NaN,NaN,The Assam Tribune,https://assamtribune.com/assam/rakesh-paul-33-...,High
19,PL-0020,2013-01-01,UPA (2004-May2014),Vyapam Police Constable Recruitment Examinatio...,Madhya Pradesh Professional Examination Board ...,State,Madhya Pradesh,Confirmed,Arrests-FIR + Probe (CBI/SIT),Impersonation and forgery in the 2013 constabl...,NaN,31.0,NaN,NaN,NaN,India TV,https://www.indiatvnews.com/news/india/2013-po...,High
33,PL-0034,2017-07-16,NDA (May2014-now),HCS (Judicial Branch) Preliminary Examination ...,Punjab & Haryana High Court,State,Haryana,Confirmed,Exam cancelled + Arrests-FIR + Probe,A High Court committee found the paper was lea...,NaN,3.0,NaN,NaN,NaN,Careers360,https://news.careers360.com/2017-hcs-exam-pape...,High
81,PL-0082,2023-05-11,NDA (May2014-now),CGPSC State Service Examination 2021 (recruitm...,Chhattisgarh Public Service Commission (CGPSC),State,Chhattisgarh,Alleged,Probe (CBI/SIT)+Arrests-FIR,CBI probe into nepotism/favouritism in recruit...,12.0,0.0,129206.0,NaN,NaN,The Tribune,https://www.tribuneindia.com/news/chhattisgarh...,High
105,PL-0106,2026-03-14,NDA (May2014-now),CGBSE Class 12 Hindi Board Examination 2026,Chhattisgarh Board of Secondary Education (CGBSE),State,Chhattisgarh,Confirmed,Exam cancelled+Retest+Arrests-FIR,Class 12 Hindi paper leaked and circulated on ...,3.0,0.0,NaN,NaN,NaN,Careers360,https://news.careers360.com/chhattisgarh-board...,Medium

Shape of Conviction Cases: (10, 18)